
(function(){String.prototype.trim=function(){var str=this;str=str.replace(/^\s\s*/,"");var ws=/\s/;var i=str.length;while(ws.test(str.charAt(--i)));return str.slice(0,i+ 1);}
var Letao=window.Letao||{};Letao={_INSTALL:function(){window.Letao=Letao;},Base:{},DAO:{},Business:{},UI:{},Page:{}};var autoComplete=null;autoComplete=function(bindObject){if(typeof autoComplete.__list=="undefined"){var __list=function(){var list=[];this.get=function(){return list;};this.set=function(arrlist){list=arrlist
return this;};this.remove=function(index){list.splice(index,1);return this;};};__list.prototype.add=function(elem){this.get().push(elem);return this;};__list.prototype.clear=function(){this.set([]);return this;};autoComplete.__list=__list;}
if(typeof autoComplete.__constructor=="undefined"){var __constructor=function(bindObject){this._bindObject=bindObject;this._focusObject=null;this._focusData=null;this._firstData=null;this._lastData=null;this._mouseBind=false;this._keyBind=false;this.uuid=null;this.lock={ajax:false,input:false};this.timer={ajax:null,input:null};this.memorize={on:false,content:{},indexer:[],maxcount:100};this.list=new autoComplete.__list();this.dom={outer:{obj:null,lable:"ul",css:{"position":"absolute","border":"1px solid #aaa","border-top":"0","background-color":"#fff"}},inner:{lable:"li",css:{"line-height":"24px","height":"24px","font-size":"12px","padding":"0 6px","border-bottom":"0","background-color":"#fff","position":"relative","cursor":"default"},focus:{"background-color":"#e2eaff"},blur:{"background-color":"#fff"}},em:{lable:"em",css:{"font-size":"12px","color":"#333","line-height":"24px","cursor":"default"}},count:{lable:"i",css:{"font-size":"10px","color":"#999","position":"absolute","right":"8px","top":"10px"}}};this.config={listStruct:{keyword:"Keyword",searchCount:"SearchCount",resultCount:"ResultCount"}};var input="";this.getInput=function(){return input;};this.setInput=function(text){input=text;return this;};var html=null;this.getHTML=function(){return html;};this.setHTML=function(text){html=text;return this;};this._focusEvent=null;var userInput="";this.getUserInput=function(){return userInput;};this.setUserInput=function(text){userInput=text;return this;};};__constructor.prototype._focus=function(jqo){this._focusObject=jqo.css(this.dom.inner.focus);return this;};__constructor.prototype._blur=function(jqo){if(!jqo){return this;}
jqo.css(this.dom.inner.blur);return this;};__constructor.prototype._focusUserInput=function(){this._focusObject=null;this._focusData=this.getUserInput();this._bindObject.val(this._focusData).focus();this.setInput(this._focusData);};__constructor.prototype._focusBatch=function(data){this._focus(data);this._focusData=this._focusObject.data("FOCUSDATA");this._bindObject.val(this._focusData).focus();this.setInput(this._focusData);};__constructor.prototype._clear=function(){this._focusObject=null;this._focusData=null;this._firstData=null;this._lastData=null;};__constructor.prototype._makeLable=function(o){var lable=o.lable,css=o.css,lableCSS="";for(var i in css){lableCSS+=i+":"+ css[i]+";";}
return{start:"<"+ lable+" style=\""+ lableCSS+"\">",end:"<\/"+ lable+">"};};__constructor.prototype.makeUUID=function(){this.uuid="autocomp"+ new Date().getTime();return this.uuid;};__constructor.prototype.makeItem=function(_item,structor,fn){if(typeof fn=="function"){return fn.call(this,_item,structor);}
else{var inner=this.dom.inner,lable=inner.lable,css=inner.css,em=this.dom.em,count=this.dom.count,input=this.getInput();if(typeof structor=="undefined"){structor=this.config.listStruct;}
var keywordKey,searchCountKey,resultCountKey,keyword=null,searchCount=null,resultCount=null,data=null;if(structor!=null){keywordKey=structor.keyword||null;searchCountKey=structor.searchCount||null;resultCountKey=structor.resultCount||null;keyword=keywordKey&&_item.hasOwnProperty(keywordKey)?_item[keywordKey]:null;searchCount=searchCountKey&&_item.hasOwnProperty(searchCountKey)?_item[searchCountKey]:null;resultCount=resultCountKey&&_item.hasOwnProperty(resultCountKey)?_item[resultCountKey]:null;}
else{keyword=_item.toString();}
data=keyword;if(typeof em.string=="undefined"){em.string=this._makeLable(em);}
var inputRegex="^(\\s*",_input=input,inputWithoutSpace=_input.replace(/\s/g,"");for(var i=0,len=inputWithoutSpace.length;i<len;i++){inputRegex+=inputWithoutSpace.charAt(i)+"\\s*";}
inputRegex+=")";var re=new RegExp(inputRegex,"i");keyword=keyword.replace(re,em.string.start+"$1"+ em.string.end);if(resultCount!=null){if(typeof count.string=="undefined"){count.string=this._makeLable(count);}
resultCount=count.string.start+ resultCount+ count.string.end;}
else{resultCount="";}
var outHTML=keyword+ resultCount;return $("<"+ lable+">").html(outHTML).css(css).data("FOCUSDATA",data);}};__constructor.prototype.makeOuter=function(){var outer=this.dom.outer,lable=outer.lable,css=outer.css,uuid=this.uuid,bindObject=this._bindObject;var jqo=$("<"+ lable+">").attr("id",uuid).css(css);var zindex=Math.floor(new Date().getTime()/ 1000);$("body").append(jqo.css({"z-index":zindex,"width":(bindObject.outerWidth()- 2)+"px","left":bindObject.offset().left+"px","top":(bindObject.offset().top+ bindObject.outerHeight())+"px"}));if(jqo.length==1){this.dom.outer.obj=jqo;}
$(window).resize(function(){jqo.css({"left":bindObject.offset().left+"px","top":(bindObject.offset().top+ bindObject.outerHeight())+"px"});});return jqo;};__constructor.prototype.makeStrong=function(){this._focusObject.html();};__constructor.prototype.makeList=function(){this._clear();var list=this.list.get(),html=null;var outer=this.dom.outer.obj;if(outer==null){var uuid=this.uuid;if(this.uuid==null){uuid=this.makeUUID();}
outer=this.makeOuter();this.bindMouse();this.bindKey();}
outer.html("");if(list==null){this.hideOuter();return this;}
var len=list.length;if(len==0){this.hideOuter();return this;}
this.showOuter();for(var i=0,s=false,itm=null;i<len;i++){itm=this.makeItem(list[i]);if(itm==null){continue;}
var jqo=this.makeItem(list[i]);if(!s){this._firstData=jqo;s=true;}
outer.append(jqo);}
if(jqo!=null){this._lastData=jqo;}
return this;};__constructor.prototype.hideOuter=function(){var outer=this.dom.outer.obj;if(outer!=null&&outer.length==1){outer.hide();}};__constructor.prototype.showOuter=function(){var outer=this.dom.outer.obj;if(outer!=null&&outer.length==1){outer.show();}}
__constructor.prototype.ajax=function(ismem){var input=this.getInput();if($.trim(input)==""){this.list.clear();this.makeList();return;}
if(typeof ismem=="undefined"||ismem){this.memorize.on=true;var m=this.memorize.content;if(typeof m[input]!="undefined"){this.list.set(m[input]);this.makeList();return;}}
$.LT_AJAX("get_auto_complete",input,this.ajaxHandler(input),"user_search",this);};__constructor.prototype.ajaxHandler=function(inputHandler){if(!inputHandler){return null;}
return function(ret){if(!Letao.Base.CheckType.IsArray(ret)){this.list.clear();this.makeList();return;}
var status=ret[0];this.list.clear();if(status=="SUCCESS"){for(var i=1,len=ret.length;i<len;i++){this.list.add({"Keyword":ret[i]});}}
if(this.memorize.on){var input=inputHandler;this.memorize.content[input]=this.list.get();var maxcount=this.memorize.maxcount;if(maxcount>0){var indexer=this.memorize.indexer;indexer.push(input);if(indexer.length>maxcount){var f=indexer.shift();delete this.memorize.content[f];}}}
this.makeList();return;};};__constructor.prototype.callback=function(ret){if(!Letao.Base.CheckType.IsArray(ret)){this.list.clear();this.makeList();return;}
var status=ret[0];this.list.clear();if(status=="SUCCESS"){for(var i=1,len=ret.length;i<len;i++){this.list.add({"Keyword":ret[i]});}}
if(this.memorize.on){var input=this.getInput();this.memorize.content[input]=this.list.get();var maxcount=this.memorize.maxcount;if(maxcount>0){var indexer=this.memorize.indexer;indexer.push(input);if(indexer.length>maxcount){var f=indexer.shift();delete this.memorize.content[f];}}}
this.makeList();return;};__constructor.prototype.listener=function(obj,sec,fn){var _this=this,_sec=typeof sec=="number"?sec:25,_fn=typeof fn=="function"?fn:function(){var lastInput=_this.getInput(),currentInput=_this._bindObject.val();if(lastInput!=currentInput){clearTimeout(_this.timer.input);_this.setInput(currentInput);_this.setUserInput(currentInput);_this.timer.input=null;_this.timer.input=setTimeout(function(){_this.ajax();},180);}};var timer=null;obj.focus(function(){timer=setInterval(_fn,_sec);}).blur(function(e){clearInterval(timer);timer=null;});$(document).bind("click",function(e){var e=e||window.event;var inner=_this.dom.inner,lable=inner.lable.toLowerCase(),emlable=_this.dom.em.lable,tar=e.target||e.srcElement,tagname=tar.tagName.toLowerCase()||tar.nodeName.toLowerCase();if(tagname!=lable&&tagname!=emlable){_this.hideOuter();}});return this;};__constructor.prototype.run=function(){if(this._bindObject==null){return this;}
return this.listener(this._bindObject);};__constructor.prototype.bindMouse=function(){var outer=this.dom.outer.obj;if(outer==null||this._mouseBind){return;}
var _this=this,inner=this.dom.inner,lable=inner.lable.toLowerCase(),focus=inner.focus,blur=inner.blur,emlable=this.dom.em.lable;outer.mouseover(function(event){var e=event||window.event,tar=e.target||e.srcElement,tagname=tar.tagName.toLowerCase()||tar.nodeName.toLowerCase();var $tar=$(tar);if(tagname!=lable){if(tagname==emlable){$tar=$tar.parent();}
else{return false;}}
if($tar==_this._focusObject){return false;}
else{_this._blur(_this._focusObject);_this._focus($tar);}
return false;});outer.mouseout(function(){_this._blur(_this._focusObject);});outer.click(function(event){var e=event||window.event,tar=e.target||e.srcElement;tagname=tar.tagName.toLowerCase()||tar.nodeName.toLowerCase(),$tar=$(tar);if(tagname!=lable){if(tagname==emlable){$tar=$tar.parent();}
else{return false;}}
_this._focusData=$tar.data("FOCUSDATA");_this._bindObject.val(_this._focusData).focus();_this._focusEvent&&_this._focusEvent.call(_this);return false;});this._mouseBind=true;};__constructor.prototype.bindKey=function(){if(this._keyBind){return;}
var _this=this;$(document).bind("keydown",function(event){var list=_this.list.get();if(list==null||list.length==0){return;}
else{var e=event||window.event,keycode=e.keyCode||e.charCode;if(keycode=="40"){if((_this._focusObject==null||_this._focusObject.length==0)&&_this._firstData!=null){_this._focusBatch(_this._firstData);return;}
_this._blur(_this._focusObject);var nextObject=_this._focusObject.next();if(nextObject.length==0){_this._focusUserInput();return;}
_this._focusBatch(nextObject);return;}
if(keycode=="38"){if((_this._focusObject==null||_this._focusObject.length==0)&&_this._lastData!=null){_this._focusBatch(_this._lastData);return;}
_this._blur(_this._focusObject);var prevObject=_this._focusObject.prev();if(prevObject.length==0){_this._focusUserInput();return;}
_this._focusBatch(prevObject);return;}
return;}});this._keyBind=true;};__constructor.prototype.bindFocusEvent=function(fn){this._focusEvent=fn;};autoComplete.__constructor=__constructor;}
return new autoComplete.__constructor(bindObject);};Letao.Base={Verify:{TestRegExp:function(re,text){re=new RegExp(re);return re.test(text);},IsEmpty:function(x){return typeof x!="string"?false:(x.trim()!=""?false:true);},IsNumber:function(x){return typeof x=="undefined"?false:(isNaN(x.toString())?false:true);},IsLetter:function(x){if(typeof x=="undefined"){return false;}
var re=/^[A-Za-z]+$/;return this.TestRegExp(re,x);},IsLowerCase:function(x){if(typeof x=="undefined"){return false;}
var re=/^[a-z]+$/;return this.TestRegExp(re,x);},IsUpperCase:function(x){if(typeof x=="undefined"){return false;}
var re=/^[A-Z]+$/;return this.TestRegExp(re,x);},IsChar:function(x){if(typeof x=="undefined"){return false;}
var re=/^\w+$/;return this.TestRegExp(re,x);},IsCharUnderline:function(x){if(typeof x=="undefined"){return false;}
var re=/^(\w*)(\_+)(\w*)$/;return this.TestRegExp(re,x);},IsTelephone:function(x){if(typeof x=="undefined"){return false;}
var re=/^(\((\d{2,5})\)|\d{2,5})?(\s*)(-?)(\s*)(\d{5,9})$/;return this.TestRegExp(re,x);},IsPhone:function(x){if(typeof x=="undefined"){return false;}
var re=/^(\+86)?1[3,5,8](\d{9})$/;return this.TestRegExp(re,x);},IsIdentityCode:function(x){if(typeof x=="undefined"){return false;}
var re=/^[1-9](\d{5})(([1-9]\d)|([1,2](\d{3})))(0[1-9]|1[0,2])(0[1-9]|[1,2]\d|3[0,1])(\d{3})([0-9Xx]+)$/;return this.TestRegExp(re,x);},IsEmail:function(x,limitSite){if(typeof limitsite=="undefined"||typeof limitSite!="string"){var re=/^(\w+)@((([A-Za-z0-9]+)\.)+)[A-Za-z]{2,4}$/g;return this.TestRegExp(re,x);}
else{var re=new RegExp("^(\\w+)@"+ limitsite+"$","g");return this.TestRegExp(re,x);}},IsShoeSize:function(x){if(typeof x=="undefined"){return false;}
var re=/^[1-4]\d(\.5)?$/;return this.TestRegExp(re,x);},IsMoreShoeSize:function(x){if(typeof x=="undefined"){return false;}
var re=/^([1-4]\d(\.5)?\/)*[1-4]\d(\.5)?$/;return this.TestRegExp(re,x);}},CheckType:{IsArray:function(obj){return obj&&typeof(obj)=="object"&&typeof(obj.length)=="number"&&typeof(obj.splice)=="function";}},Event:(function(){var _event={pageX:0,pageY:0,Set:function(){var arg=arguments;if(arg.length==0){arg=null;return this;}
if(arg.length==1&&typeof arg[0]=="object"){for(var i in arg[0]){this[i]=arg[0][i];}
arg=null;return this;}
if(arg.length==2){opt[arg[0]]=arg[1];arg=null;return this;}}}
function setEvent(e){_event.pageX=e.clientX+ $(window).scrollLeft();_event.pageY=e.clientY+ $(window).scrollTop();}
return function(e){if(typeof e!="undefined"){e=e||event;setEvent(e);}
return _event;}})()};Letao.DAO={ShoppingCart:{GetProduct:function(callback){$.LT_AJAX("get_trolley_product",null,callback,"user_trolley");},SetProduct:function(pid,size,count,parentid,parentsize,saletype,promoid,callback){if(typeof parentid=="function"){callback=parentid;parentid=null;}
$.LT_AJAX("set_trolley_product",[pid,size,count,parentid||null,parentsize||null,saletype||0,promoid||0],callback,"user_trolley");},RemoveProduct:function(pid,size,parentid,parentsize,saletype,promoid,callback){if(typeof parentid=="function"){callback=parentid;parentid=null;}
$.LT_AJAX("remove_trolley_product",[pid,size,parentid||null,parentsize||null,saletype||0,promoid||0],callback,"user_trolley");},ClearProduct:function(callback){$.LT_AJAX("clear_trolley_product",null,callback,"user_trolley");},SaveProductIDs:function(data,callback){$.LT_AJAX("save_trolley_productIds",[data],callback,"user_trolley");},SaveSingleProIDS:function(data,callback){$.LT_AJAX("save_trolley_SingleProIds",[data],callback,"user_trolley");},AddSingleProIds:function(data,callback){$.LT_AJAX("add_trolley_singleproids",[data],callback,"user_trolley");},RemoveSingleProIds:function(data,callback){$.LT_AJAX("remove_trolley_singleproids",[data],callback,"user_trolley");}}}
Letao.Business={ClickStat:function(elem){if(!elem){return false;}},WebToolkit:{AddFavorite:function(title,url){if(typeof title!="string"||typeof url!="string"){return false;}
try{if(window.sidebar){window.sidebar.addPanel(title,url,"");}
else if(document.all){window.external.AddFavorite(url,title);}
else if(window.opera&&window.print){return true;}}
catch(e){alert("您的浏览器相关文件已缺失或损坏,请按Ctrl+D将乐淘网址添加到您的收藏夹/书签中");}},CheckBrowser:function(){return window.sidebar||document.all;},Close:function(){$.LT_AJAX("favorite_close",null,null,"user_site_topmenu");},Off:function(){$.LT_AJAX("favorite_off",null,null,"user_site_topmenu");}},XHR:{CheckResult:function(r){var status="";if(!Letao.Base.CheckType.IsArray(r)){return"ERROR";}
status=r[0].toString();return status;}},ShoppingCart:(function(){var Data=null;var PromotionData=null;var alertData="";var isLock=false;var callfunc=null;function Lock(unclear){isLock=true;if(typeof unclear=="undefined"||!unclear){Data=null;}}
function Unlock(){isLock=false;}
function IsValidSerializationProductCode(pid,size){pid+="";size+="";if(pid.length!=9||size.length!=3){return false;}
return true;}
function CallbackShoppingCart(xhrResult){Unlock();if(Letao.Business.XHR.CheckResult(xhrResult)!="SUCCESS"){alertData="";if(Letao.Business.XHR.CheckResult(xhrResult)=="ALERT"){alertData=xhrResult[1];}
return false;}
Letao.Business.ShoppingCart.Set(xhrResult[1]);if(xhrResult.length==6){var pname=xhrResult[2],pprice=xhrResult[3],plink=xhrResult[4],ptype=xhrResult[5];var pdata=Letao.Business.ShoppingCart.SerializePromotionData(pname,pprice,plink,ptype);Letao.Business.ShoppingCart.SetPromotionData(pdata);}
else{PromotionData=null;}
if(callfunc!=null){callfunc.call(window,xhrResult[1]);}
callfunc=null;}
return{Get:function(func){if(isLock){return false;}
Lock();if(typeof func=="function"){callfunc=null;callfunc=func;}
Letao.DAO.ShoppingCart.GetProduct(CallbackShoppingCart);},Set:function(data){if(isLock){return false;}
Lock();this.SetData(data);Unlock();},Add:function(pid,size,count,parentid,parentsize,saletype,promoid,func){if(isLock){return false;}
Lock();if(!IsValidSerializationProductCode(pid,size)){Unlock();return false;}
if(typeof func=="function"){callfunc=null;callfunc=func;}
Letao.DAO.ShoppingCart.SetProduct(pid,size,count,parentid,parentsize,saletype,promoid,CallbackShoppingCart);},Substract:function(pid,size,count,parentid,parentsize,saletype,promoid,func){return this.Add(pid,size,count,parentid,parentsize,saletype,promoid,func);},Remove:function(pid,size,parentid,parentsize,saletype,promoid,func){if(isLock){return false;}
Lock();if(!IsValidSerializationProductCode(pid,size)){Unlock();return false;}
if(typeof func=="function"){callfunc=null;callfunc=func;}
Letao.DAO.ShoppingCart.RemoveProduct(pid,size,parentid,parentsize,saletype,promoid,CallbackShoppingCart);},GetData:function(){return Data;},SetData:function(data){Data=data;},GetAlert:function(){return alertData;},SetPromotionData:function(pdata){PromotionData=pdata;},SerializePromotionData:function(pname,pprice,plink,ptype){return{PromotionName:pname,PromotionPrice:pprice,PromotionLink:plink,PromotionType:ptype}},GetPromotionData:function(){return PromotionData;},Clear:function(func){if(isLock){return false;}
Lock();if(typeof func=="function"){callfunc=null;callfunc=func;}
Letao.DAO.ShoppingCart.ClearProduct(CallbackShoppingCart);},SetCartIds:function(data,func){if(data.length<=0){return;}
Letao.DAO.ShoppingCart.SaveProductIDs(data,func);},SaveSingleProIDS:function(data,func){if(data.length<=0){return;}
Letao.DAO.ShoppingCart.SaveSingleProIDS(data,func);},AddSingleProIds:function(data,func){if(data.left<=0){return;}
Letao.DAO.ShoppingCart.AddSingleProIds(data,func);},RemoveSingleProIds:function(data,func){if(data.left<=0){return;}
Letao.DAO.ShoppingCart.RemoveSingleProIds(data,func);}}})()}
Letao.UI={MousePosition:function(e){e=e||window.event;var X=e.pageX||e.clientX+ document.body.scrollLeft,Y=e.pageY||e.clientY+ document.body.scrollTop;return{positionX:X,positionY:Y}},GetArea:function(jqelem){if(jqelem.selector=="document"){return{height:$(document).height(),width:$(document).width()}}
if(jqelem.css("overflow")!="hidden"){return{height:jqelem.height(),width:jqelem.width()}}
var _jqelem=jqelem.clone();_jqelem.css({"display":"block","position":"absolute","overflow":"visible"});return{height:_jqelem.height(),width:_jqelem.width()}},ModeWindow:(function(){var ConstructorInitial=null;function constructor(){var defaultOption={ID:null,Title:"ModeWindow - MacroX",Content:"Text in content",Statusbar:null,Parent:null,CloseIcon:{ImageSrc:"default",Width:10,Height:12,func:null},Backover:true,Frameover:false,Drag:false,ContainOut:false,CSS:{border:"1px solid #ddd",display:"none",padding:"1px",position:"absolute","background-color":"#fff"},TitleCSS:{"text-indent":"20px","font-size":"14px","color":"#fff","background-color":"#aaa","line-height":"22px","height":"22px","position":"relative"},ContentCSS:{"padding":"16px 20px","line-height":"18px"},StatusbarCSS:{},AutoIndex:true};var defaultShowOption={reshow:false,showType:"fade",position:"center",relativeTop:0,relativeLeft:0,bindObject:null};var windowAssembly=[];function _CreateWindow(opt){var windowID=opt.ID;if(!windowID){return null;}
if($("#"+ windowID).length>0){return $("#"+ windowID);}
var parent=(opt.Parent==null||$(opt.Parent).length==0)?$("body"):$(opt.Parent);parent.append($("<div>").attr("id",opt.ID).css(opt.CSS));return $("#"+ windowID);}
function _SetWindowConstruction(w,opt,isreload){isreload=typeof isreload=="boolean"?isreload:false;w.isSet=w.obj.html()==""?false:true;if(w&&w.isSet&&!isreload){return w;}
if(isreload){w.obj.html("");w.obj.css(opt.CSS);}
w.obj.append($("<div>").attr("id","w_uuid_"+ opt.ID).css(opt.TitleCSS).html(opt.Title));w.obj.append($("<div>").attr("id","content_uuid_"+ opt.ID).css(opt.ContentCSS).html(opt.Content));w.obj.append($("<div>").css(opt.StatusbarCSS).html(opt.Statusbar));w.isSet=true;w.ID=opt.ID;w.UUID="w_uuid_"+ opt.ID;w.Option=opt;w.Backover=_SetBackover(w);w.Frameover=_SetFrameover(w);w.CloseIcon=_SetCloseIcon(w);w.Drag=_MoveWindow(w);w.IsShow=false;return w;}
function _SetCloseIcon(w){if(w.Option.CloseIcon==null){return;}
var closeIcon=w.Option.CloseIcon;if(closeIcon.ImageSrc==null){return;}
var closeIconImage=closeIcon.ImageSrc=="default"?"http://img.letao.com/letaozu/images/letaozuUI/close.gif":closeIcon.ImageSrc;var closeIconPosition="5px";$("#"+ w.UUID).append($("<div>").attr({"id":w.UUID+"_closeicon"}).css({width:closeIcon.Width+"px",height:closeIcon.Height+"px",position:"absolute",right:closeIconPosition,top:closeIconPosition,cursor:"pointer",background:"url("+ closeIconImage+") no-repeat 0 0"}).hover(function(){$(this).css({"background-position":"right 0"})},function(){$(this).css({"background-position":"0 0"})}).bind("click",function(){_WindowClose(w,undefined,closeIcon.func);}));return $("#"+ w.UUID+"_closeicon");}
function _SetBackover(w){if(w.Option.Backover==false){return null;}
if($("#MW_BACKOVER").length==0){$("body").append($("<div>").attr("id","MW_BACKOVER").css({"background-color":"#ddd","position":"fixed","top":"0","left":"0","width":"100%","height":"100%","display":"none","opacity":0.3}));var isIE=!!window.ActiveXObject;var isIE6=isIE&&!window.XMLHttpRequest;if(isIE6){$("#MW_BACKOVER").css({"position":"absolute"});}}
return{obj:$("#MW_BACKOVER"),Show:function(){var zIndex=parseInt(new Date().getTime()/ 1000);var _overwidth=($(window).width()>$(document).width())?$(window).width():$(document).width();var _overheight=($(window).height()>$(document).height())?$(window).height():$(document).height();$("#MW_BACKOVER").css({"width":_overwidth+"px","height":_overheight+"px","z-index":zIndex,"display":"block"});},Hide:function(){$("#MW_BACKOVER").hide();}}}
function _SetFrameover(w){if(w.Option.Frameover==false){return null;}
if($("#MW_FRAMEOVER").length==0){$("body").append($("<div>").attr("id","MW_FRAMEOVER").css({"background-color":"#fff","position":"absolute","display":"none","top":"0","left":"0","overflow":"hidden"}).html("<iframe border=\"0\" style=\"border:0;margin:0;padding:0\"></iframe>"));}
return{obj:$("#MW_FRAMEOVER"),Show:function(){var zIndex=1000;var _object=w.obj;var _overwidth=_object.outerWidth();var _overheight=_object.outerHeight();var _overtop=_object.offset().top;var _overleft=_object.offset().left;$("#MW_FRAMEOVER").css({"width":_overwidth+"px","height":_overheight+"px","z-index":zIndex,"top":_overtop+"px","left":_overleft+"px","display":"block"});},Hide:function(){$("#MW_FRAMEOVER").hide();}}}
function _WindowShow(w,showoption,prevoption,func){var showopt=$.extend({},defaultShowOption,showoption);if(w.Backover!=null&&w.Backover.obj.css("display")=="none"){w.Backover.Show();}
var positionTop="auto",positionLeft="auto",positionRight="auto",positionBottom="auto";if(showopt.reshow){if(showopt.showType=="fade"){w.obj.stop(true,true).fadeIn("slow");}
else{w.obj.show();}
return w;}
var modeWindow=w.obj;switch(showopt.position){case"center":positionTop=$(window).height()/ 2 - modeWindow.height() / 2 + $(document).scrollTop() + showopt.relativeTop;positionLeft=$(document).width()/ 2 - modeWindow.width() / 2 + $(document).scrollLeft() + showopt.relativeLeft;break;case"abscenter":positionTop=$(document).height()/ 2 - modeWindow.height() / 2 + $(document).scrollTop() + showopt.relativeTop;positionLeft=$(document).width()/ 2 - modeWindow.width() / 2 + $(document).scrollLeft() + showopt.relativeLeft;break;case"left-top-corner":positionTop=0;positionLeft=0;break;case"left-bottom-corner":positionLeft=0;positionBottom=0;break;case"right-top-corner":positionRight=0;positionTop=0;break;case"right-bottom-corner":positionRight=0;positionBottom=0;break;case"bindto":if(showopt.bindObject.length!=0){positionTop=showopt.bindObject.offset().top+ showopt.relativeTop;positionLeft=showopt.bindObject.offset().left+ showopt.relativeLeft;}
else{positionTop=$(window).height()/ 2 - modeWindow.height() / 2 + $(document).scrollTop() + showopt.relativeTop;positionLeft=$(document).width()/ 2 - modeWindow.width() / 2 + $(document).scrollLeft() + showopt.relativeLeft;}
break;default:positionTop=$(window).height()/ 2 - modeWindow.height() / 2 + $(document).scrollTop() + showopt.relativeTop;positionLeft=$(document).width()/ 2 - modeWindow.width() / 2 + $(document).scrollLeft() + showopt.relativeLeft;}
var zIndex=parseInt(new Date().getTime()/ 1000 + 1);modeWindow.css({top:positionTop=="auto"?positionTop:positionTop+"px",left:positionLeft=="auto"?positionLeft:positionLeft+"px",right:positionRight=="auto"?positionRight:positionRight+"px",bottom:positionBottom=="auto"?positionBottom:positionBottom+"px"});if(w.Option&&w.Option.AutoIndex){modeWindow.css("z-index",zIndex);}
if(showopt.showType=="fade"){modeWindow.stop(true,true).fadeIn("slow",func);}
else{modeWindow.show(func);}
if(w.Frameover!=null&&w.Frameover.obj.css("display")=="none"){w.Frameover.Show();}
w.IsShow=true;return w;}
function _WindowClose(w,windowonly,func){w.obj.hide(0,func);if(w.Frameover!=null){w.Frameover.Hide();}
w.IsShow=false;if(windowAssembly.length>0){for(var i=0;i<windowAssembly.length;i++){if(w!=windowAssembly[i]&&windowAssembly[i].IsShow&&windowAssembly[i].Backover!=null){return w;}}
if((typeof windowonly=="undefined"||windowonly&&typeof windowonly=="boolean"&&windowonly==false)&&w.Backover!=null){w.Backover.Hide();}}
return w;}
function _MoveWindow(w){if(!w.Option.Drag){return false;}
var titleObj=$("#"+ w.UUID);var windowMove=window._IS_WINDOW_MOVING||false;var windowParent=(w.Option.Parent==null||$(w.Option.Parent).length==0)?$("body"):$(w.Option.Parent);w.obj.bind("mousedown",function(){var zIndex=parseInt(new Date().getTime()/ 1000) + 1;var _left=$(this).position().left+"px",_top=$(this).position().top+"px";$(this).css({left:_left,top:_top,right:"auto",bottom:"auto"});if(w.Option.AutoIndex){$(this).css("z-index",zIndex);}});titleObj.bind("mousedown",function(e){if(windowMove){return false;}
windowMove=true;var mousePosition=Letao.UI.MousePosition(e);var xPoint=mousePosition.positionX,yPoint=mousePosition.positionY;var windowTop=w.obj.position().top,windowLeft=w.obj.position().left;var zIndex=parseInt(new Date().getTime()/ 1000);w.obj.css({"opacity":0.5})
$(document).mousemove(function(e){if(!windowMove){return false;}
window.getSelection?window.getSelection().removeAllRanges():document.selection.empty();var m=Letao.UI.MousePosition(e);var xPointNow=m.positionX,yPointNow=m.positionY;var relativeLeft=xPointNow- xPoint,relativeTop=yPointNow- yPoint;var wt=(windowTop+ relativeTop<=windowParent.offset().top&&!w.Option.ContainOut)?windowParent.offset().top:windowTop+ relativeTop,wl=(windowLeft+ relativeLeft<=windowParent.offset().left&&!w.Option.ContainOut)?windowParent.offset().left:windowLeft+ relativeLeft;if(!w.Option.ContainOut){var _overwidth,_overheight;if(w.Option.Parent==null||$(w.Option.Parent).length==0){_overwidth=($(window).width()>$(document).width())?$(window).width():$(document).width();_overheight=($(window).height()>$(document).height())?$(window).height():$(document).height();}
else{_overwidth=windowParent.outerWidth();_overheight=windowParent.outerHeight();}
wt=(wt>=_overheight- w.obj.outerHeight()+ windowParent.offset().top)?_overheight- w.obj.outerHeight()+ windowParent.offset().top:wt;wl=(wl>=_overwidth- w.obj.outerWidth()+ windowParent.offset().left)?_overwidth- w.obj.outerWidth()+ windowParent.offset().left:wl;}
w.obj.css({"left":wl+"px","top":wt+"px"});return false;});$(document).mouseup(function(e){windowMove=false;w.obj.css({"opacity":1});$(this).unbind("mousemove").unbind("mouseup");return false;});});return w;}
return function(option){var windowObject=null;var opt=$.extend({},defaultOption,option);opt.CSS=$.extend({},defaultOption.CSS,option.CSS);opt.TitleCSS=$.extend({},defaultOption.TitleCSS,option.TitleCSS);opt.ContentCSS=$.extend({},defaultOption.ContentCSS,option.ContentCSS);opt.CloseIcon=$.extend({},defaultOption.CloseIcon,option.CloseIcon);var prevShowOption=null;windowObject=_CreateWindow(opt);if(!windowObject){throw new Error("Error : [Letao.UI.ModeWindow] Option.ID is undefined");return false;}
windowObject={obj:windowObject,isSet:false};windowObject=_SetWindowConstruction(windowObject,opt,false);if(!windowObject.isSet){throw new Error("Error : [Letao.UI.ModeWindow] Window Object is unconstructed");return false;}
windowAssembly.push(windowObject);return{GetObject:function(){return windowObject;},Show:function(showoption,func){if(typeof func!="function"){func=null;}
windowObject=_WindowShow(windowObject,showoption,prevShowOption,func);if(prevShowOption==null){prevShowOption=showoption;}},Close:function(windowonly,func){if(typeof func!="function"){func=null;}
windowObject=_WindowClose(windowObject,windowonly,func);},Reload:function(windowoption,showoption){var opt=$.extend({},defaultOption,windowoption);opt.CSS=$.extend({},defaultOption.CSS,windowoption.CSS);opt.TitleCSS=$.extend({},defaultOption.TitleCSS,windowoption.TitleCSS);opt.ContentCSS=$.extend({},defaultOption.ContentCSS,windowoption.ContentCSS);windowObject=_SetWindowConstruction(windowObject,opt,true);windowObject=this.Show(showoption);},SetContent:function(content){var _id="content_uuid_"+ windowObject.ID;if($("#"+ _id).length==1){$("#"+ _id).html(content);}},SetTitle:function(title){var _id="w_uuid_"+ windowObject.ID;if($("#"+ _id).length==1){$("#"+ _id).html(title);_SetCloseIcon(windowObject);}}}}}
return function(option){if(ConstructorInitial==null)
ConstructorInitial=constructor();return ConstructorInitial(option);}})(),YellowFade:(function(){var yfObject=null;var loadObject={object:null,_createYellowFadeObject:function(){var yf=$("<span>").css({"border":"1px solid #FFE591","background":"url(http://img.letao.com/letaozu/images/letaozuUI/ajax-loader-smallsnake.gif) no-repeat scroll 8px center #FFFAEA","position":"absolute","padding":"4px 16px 4px 30px","opacity":0,"z-index":9999});$("body").append(yf);this.object=yf;return yf;}};var noloadObject={object:null,_createYellowFadeObject:function(){var yf=$("<span>").css({"border":"1px solid #FFE591","position":"absolute","background-color":"#FFFAEA","padding":"4px 16px","opacity":0,"z-index":9999});$("body").append(yf);this.object=yf;return yf;}};function getShowOption(ev,direction){var zIndex=parseInt(new Date().getTime()/ 1000) + 10;switch(direction){case"up":return{from:{left:ev().pageX+ 16,top:ev().pageY+ 30,display:"block","z-index":zIndex},to:{top:ev().pageY+ 10,opacity:0.8}};break;case"left":return{from:{left:ev().pageX+ 100,top:ev().pageY+ 10,display:"block","z-index":zIndex},to:{left:ev().pageX+ 20,opacity:0.8}};break;}
return null;}
function getHideOption(ev,direction){switch(direction){case"up":return{top:ev.pageY- 50,opacity:0};break;case"right":return{left:ev.pageX+ 120,opacity:0};break;}
return{top:ev.pageY- 50,opacity:0};}
return{Show:function(message,ev,isload,direction){ev=ev||Letao.Base.Event;var _yfObject=typeof isload=="undefined"||isload?loadObject:noloadObject;var direction=(typeof direction=="undefined"?"up":direction);if(_yfObject.object==null){yfObject=_yfObject._createYellowFadeObject();}
else{yfObject=_yfObject.object;}
yfObject.stop(true,true);var op=getShowOption(ev,direction);yfObject.html(message).css(op.from).animate(op.to,500);},Hide:function(direction){var direction=(typeof direction=="undefined"?"up":direction);var ev=Letao.Base.Event();var opt=getHideOption(ev,direction);yfObject.animate(opt,500,function(){$(this).hide();});}}})(),ShoppingCart:{Data:null,SerializationData:function(data,pdata){var CartInfo={totalCount:0,totalPrice:0,noStockCount:0};var dtNoStock={Rows:[]},dr=data.Rows;var pcount,pprice;var html="";if(dr.Count==0){html+="<div style=\"height:20px;line-height:20px;font-size:14px;color:#ccc;text-align:center;padding:20px 0\">"+"<img src=\"http://img.letao.com/letaozu/images/ui/cart.gif\" alt=\"\" />&nbsp;&nbsp;"+"您的购物车中还没有任何商品！</div>";}
else{html+="<table id=\"shopping_trolley_innertable\">"+"<thead><tr>"+"<td class=\"prod_image\"></td>"+"<td class=\"prod_name\"></td>"+"<td class=\"prod_count\"></td>"+"</tr></thead>";for(var i=0;i<dr.Count;i++){if(dr[i]["HasStock"]==true){if(CartInfo.totalCount==0)
html+="<tbody>";}
html+=this.BuildProduct(dr[i],CartInfo,dtNoStock);}
if(CartInfo.totalCount>0)
html+="</tbody>";html+="<tfoot>";if(CartInfo.totalCount>0){var realTotalPrice=CartInfo.totalPrice;html+="<tr>"+"<td colspan=\"3\" class=\"prodtotal\" style=\"height:18px;line-height:18px;padding-top:18px\">"+"<input type=\"hidden\" id=\"hid_prod_count\" value=\""+ CartInfo.totalCount+"\" />"+"数量总计："+ CartInfo.totalCount+"件&nbsp;&nbsp;&nbsp;"+"商品总额：<strong>"+ realTotalPrice.toFixed(2)+"元</strong>";if(pdata!=null){html+="</td></tr><tr><td class=\"prodtotal\" colspan=\"3\">"+"满立减：<strong style=\"color:#008CD6;margin-right:2px\">-"+
pdata.PromotionPrice+"元</strong>";var _promotion_desc=pdata.PromotionName;if(_promotion_desc.length>25)_promotion_desc=_promotion_desc.slice(0,25)+"...";if(pdata.PromotionLink==""){html+="("+ _promotion_desc+")";}
else{html+="<a href=\""+ pdata.PromotionLink+"\" target=\"_blank\" style=\"color:#999\" title=\""+ pdata.PromotionName+"\">"+"("+ _promotion_desc+")"+"</a>";}
html+="</td></tr>";realTotalPrice=realTotalPrice- pdata.PromotionPrice;}
html+="<tr>"+"<td colspan=\"3\" style=\"text-align:right\">"+"应付商品金额:"+"<i class=\"ltbigprice\">"+ realTotalPrice.toFixed(2)+"元</i>"+"</td></tr>"+"<tr><td colspan=\"3\" class=\"prodtotal\" style=\"padding-bottom:12px\">"+"<a class=\"btn_clear\" href=\"javascript:void(0);\" onclick=\"javascript:if(!confirm('您确定要清空购物车吗？'))return false;Letao.UI.ShoppingCart.ClearCart().SetCartInner(function(){Letao.UI.ShoppingCart.SetCartCount('fnMyShopcart1','购物车','件','#f00',true);});\">清空购物车</a>"+"<a href=\"/letaozu/pay/usercart.aspx\" target=\"_blank\"><img src=\"/letaozu/images/ui/sc_buy5.gif\" class=\"btn_toorder\" alt=\"\" /></a>"+"</td></tr>";}
if(dtNoStock.Rows.length!=0){var drNS=dtNoStock.Rows;html+="<tr>"+"<td colspan=\"3\" style=\"text-align:left;color:#999;border-bottom:1px solid #eee;padding:10px 0 5px\">"+"以下商品已售罄，暂无法购买"+"</td></tr>";for(var i=0;i<drNS.length;i++){html+=this.BuildProduct(drNS[i],CartInfo);}}
html+="</tfoot></table>";}
var returnObject={Count:CartInfo.totalCount+ CartInfo.noStockCount,Price:CartInfo.totalPrice,HTML:html};return returnObject;},BuildProduct:function(dr,CartInfo,dtNoStock){var pid,pname,pimage,psize,prsize,pcount,pprice,purl,pvprice;var parentid=null,parentsize=null,saletype=0,promoid=0;var html="",HasStock=dr["HasStock"];var subProduct,HasSubProduct=false;var ppromo,priceName="乐淘价";if(!HasStock&&typeof dtNoStock!="undefined"){dtNoStock.Rows.push(dr);return"";}
pid=dr["ProductID"].toString().substring(0,9);pname=dr["ProductName"].toString();pimage=dr["Image"].toString();psize=dr["ProductSize"].toString();prsize=dr["ProductID"].toString().substring(9,12);pcount=Math.floor(dr["ProductNum"]);pprice=parseFloat(dr["letao_price_discount"]);ppromo=parseInt(dr["letao_price_discount_type"]);purl=dr["StaticURL"].toString();pvprice=parseFloat(dr["letao_vprice"]);parentid=dr["ParentID"].toString();saletype=Math.floor(dr["SaleType"]);promoid=Math.floor(dr["PromoID"]);subProduct=dr["SubProduct"];if(ppromo==100){priceName="黄金会员";}
if(ppromo==101){priceName="钻石会员";}
if(subProduct!=null&&subProduct.Rows.length>0)
HasSubProduct=true;if(parentid!=null&&parentid.length==12){parentsize=parentid.substring(9,12);parentid=parentid.substring(0,9);}
else{parentsize=null;}
html+="<tr><td class=\"prod_image\">"+"<a href=\""+ purl+"\" target=\"_blank\">"+"<img src=\""+ pimage+"\" alt=\"\" />"+"</a></td>"+"<td class=\"prod_name";if(!HasStock){html+=" nostock";}
html+="\"><a href=\""+ purl+"\" target=\"_blank\">"+ pname+"</a></td>";if(HasStock&&saletype!=6){html+="<td><span class=\"tly_prodadd\" "+"onclick=\"javascript:Letao.UI.ShoppingCart.AddProduct('"+ pid+"','"+ prsize+"',1,'"+ parentid+"','"+ parentsize+"',"+ saletype+","+ promoid+").SetCartInner(function(){Letao.UI.ShoppingCart.SetCartCount('fnMyShopcart1','购物车','件','#f00',true);},this);\" "+"onmouseover=\"javascript:$(this).addClass('tly_prodadd_hover');\""+"onmouseout=\"javascript:$(this).removeClass('tly_prodadd_hover');\" "+"title=\"商品数量+1\">"+"</span>"+"<span class=\"tly_prodnum\">"+ pcount+"</span>"+"<span class=\"tly_prodsubstract\" "+"onclick=\"javascript:if($(this).prev('.tly_prodnum').html()=='1'){if(!confirm('您确定要将该件商品从购物车中删除吗？'))return false;};Letao.UI.ShoppingCart.SubstractProduct('"+ pid+"','"+ prsize+"',-1,'"+ parentid+"','"+ parentsize+"',"+ saletype+","+ promoid+").SetCartInner(function(){Letao.UI.ShoppingCart.SetCartCount('fnMyShopcart1','购物车','件','#f00',true);});\" "+"onmouseover=\"javascript:$(this).addClass('tly_prodsubstract_hover');\""+"onmouseout=\"javascript:$(this).removeClass('tly_prodsubstract_hover');\" "+"title=\""+(pcount==1?"删除此商品":"商品数量-1")+"\">"+"</span>";}
else{html+="<td style=\"text-align:right;color:#999\">数量："+ pcount+"件";}
html+="</td></tr>"+"<tr class=\"prod_price\">"+"<td style=\"vertical-align:top;text-align:left\">";if(saletype==6){if(pprice>0)
html+="<span class=\"giftflag\">搭配</span>";else if(pprice==0)
html+="<span class=\"giftflag\">赠品</span>";}
html+="</td>"+"<td style=\"text-align:left\">专柜价："+ pvprice+"元&nbsp;&nbsp;&nbsp;&nbsp;"+ priceName+"：<i>"+ pprice+"元</i></td>"+"<td style=\"text-align:right\">[";if(HasStock){html+="<a href=\"javascript:void(0);\" onclick=\"javascript:Letao.UI.ShoppingCart.MoveToCollect($(this),'"+ pid+"','"+ prsize+"')\">移入收藏夹</a>";}
else{html+="<a href=\"javascript:void(0);\" onclick=\"javascript:Letao.UI.ShoppingCart.RemoveProduct('"+ pid+"','"+ prsize+"','"+ parentid+"','"+ parentsize+"',"+ saletype+","+ promoid+").SetCartInner(function(){Letao.UI.ShoppingCart.SetCartCount('fnMyShopcart1','购物车','件','#f00',true);});\">移除</a>";}
html+="]</td></tr>";if(HasStock){CartInfo.totalCount+=pcount;CartInfo.totalPrice+=pprice*pcount;}
else{CartInfo.noStockCount+=pcount;}
if(HasSubProduct){for(var i=0,len=subProduct.Rows.length;i<len;i++){var drSub=subProduct.Rows[i];html+=arguments.callee(drSub,CartInfo,dtNoStock);}}
return html;},GetCart:function(func){this.Data=null;Letao.Business.ShoppingCart.Get(func);return this;},AddProduct:function(pid,size,count,parentid,parentsize,saletype,promoid,func){this.Data=null;Letao.Business.ShoppingCart.Add(pid,size,count,parentid,parentsize,saletype,promoid,func);return this;},SubstractProduct:function(pid,size,count,parentid,parentsize,saletype,promoid,func){this.Data=null;Letao.Business.ShoppingCart.Substract(pid,size,count,parentid,parentsize,saletype,promoid,func);return this;},RemoveProduct:function(pid,size,parentid,parentsize,saletype,promoid,func){this.Data=null;Letao.Business.ShoppingCart.Remove(pid,size,parentid,parentsize,saletype,promoid,func);return this;},ClearCart:function(func){this.Data=null;Letao.Business.ShoppingCart.Clear(func);return this;},CartObject:null,ShoppingCartModeWindow:function(data){var mw=Letao.UI.ModeWindow({ID:"letaoShoppingCart",Title:"我的购物车",Content:data,CSS:{width:"402px",border:"2px solid #d10042"},TitleCSS:{"background-color":"#f2f2f2",color:"#333","font-weight":"700"},ContentCSS:{width:"380px",padding:"5px 10px 15px"},CloseIcon:{ImageSrc:null},Backover:false,Drag:true});if(this.CartObject==null){this.CartObject=mw;var header=Letao.Page.HeaderFooter;$("#letaoShoppingCart").hover(function(){clearTimeout(header._CartTimer);header._CartTimer=null;},function(){header._CartTimer=setTimeout(function(){mw.Close();},200);});}
return mw;},MoveToCollect:function(obj,prodid,size){$.LT_AJAX("add_user_collection",prodid,function(al_return){if(al_return&&al_return[0]=="SUCCESS"){Letao.Base.Event().Set({pageX:obj.offset().left- 170,pageY:obj.offset().top- 10});Letao.UI.YellowFade.Show("收藏商品成功！",Letao.Base.Event,true,"left");setTimeout(function(){Letao.UI.YellowFade.Hide("right");},1600);}
else{if(al_return=="ERROR:用户未登录"){Letao.Base.Event().Set({pageX:obj.offset().left- 90,pageY:obj.offset().top- 10});Letao.UI.YellowFade.Show("请您登录后再收藏商品！",Letao.Base.Event,true,"left");setTimeout(function(){Letao.UI.YellowFade.Hide("right");},1600);}
else{alert(al_return);}}},"user_collect");},Show:function(showoption,func){var cartData=this.Data;if(cartData==null){cartData=Letao.Business.ShoppingCart.GetData();var loadingData="<div style=\"padding:30px;background:url(http://img.letao.com/letaozu/images/load/ajax-loader.gif) no-repeat center center\"></div>";Letao.UI.ShoppingCart.ShoppingCartModeWindow(loadingData).Show(showoption);if(cartData==null){var _accepttimes=500;var _timer=setInterval(function(){if(!_accepttimes--){clearInterval(_timer);return;}
cartData=Letao.Business.ShoppingCart.GetData();if(cartData!=null){clearInterval(_timer);var pData=Letao.Business.ShoppingCart.GetPromotionData();cartData=Letao.UI.ShoppingCart.Data=Letao.UI.ShoppingCart.SerializationData(cartData,pData);Letao.UI.ShoppingCart.CartObject.SetContent(cartData.HTML);if(typeof func=="function"){func();}
cartData=null;}},13);}}
else{showoption.reshow=true;Letao.UI.ShoppingCart.ShoppingCartModeWindow(cartData).Show(showoption);if(typeof func=="function"){func();}
cartData=null;}},SetCartInner:function(func,elem){var cartData=this.Data;if(cartData==null){cartData=Letao.Business.ShoppingCart.GetData();if(cartData==null){var _accepttimes=20;var _timer=setInterval(function(){if(!_accepttimes--){clearInterval(_timer);var alertData=Letao.Business.ShoppingCart.GetAlert();if(alertData!=""){if(typeof elem=="undefined")
alert(alertData);else{var obj=$(elem);if(typeof obj.offset=="undefined"||typeof obj.offset!="function"){alert(alertData);return;}
Letao.Base.Event().Set({pageX:obj.offset().left- 170,pageY:obj.offset().top- 15});Letao.UI.YellowFade.Show(alertData,Letao.Base.Event,true,"left");setTimeout(function(){Letao.UI.YellowFade.Hide("right");},1600);}}
return;}
cartData=Letao.Business.ShoppingCart.GetData();if(cartData!=null){clearInterval(_timer);var pData=Letao.Business.ShoppingCart.GetPromotionData();cartData=Letao.UI.ShoppingCart.Data=Letao.UI.ShoppingCart.SerializationData(cartData,pData);Letao.UI.ShoppingCart.CartObject.SetContent(cartData.HTML);if(typeof func=="function"){func();}
cartData=null;}},13);}}},SetCartCount:function(elemid,prevstring,sufixstring,color,ishaveparentheses){var Cart=Letao.UI.ShoppingCart;if(Cart.Data!=null&&typeof Cart.Data.Count!="undefined"&&$("#"+ elemid).length==1){if(typeof color!="undefined"){prevstring+="<i>";sufixstring="</i>"+ sufixstring;}
if(typeof ishaveparentheses=="boolean"&&ishaveparentheses){prevstring+="";sufixstring=""+ sufixstring;}
if($("#"+ elemid).parents(".manwill").length>0){$("#"+ elemid).html("<img src=\"/manwill/images/v2/goshopping.jpg\" alt=\"购物车\">");$("#lttopcart.manwill i:first").text(0).hide();}
else{$("#"+ elemid).html(prevstring+ Cart.Data.Count+ sufixstring);}
if(Cart.CartObject!=null){Cart.CartObject.SetContent(Cart.Data.HTML);}}},GetCartCount:function(){if(Letao.UI.ShoppingCart.Data==null){return 0;}
var count=Letao.UI.ShoppingCart.Data.Count;if(typeof count=="undefined"||count==null){return 0;}
return count;}},ShoppingCartV3:{Data:null,SerializationData:function(data,pdata){var CartInfo={totalCount:0,totalPrice:0,noStockCount:0};var dtNoStock={Rows:[]},dr=data.Rows;var pcount,pprice;var html="";if(dr.Count==0){html+="<div class='cartnull shopping'>                         ";html+="<a class='cartdetail fr shopping' href='/letaozu/pay/usercart.aspx'>全屏查看</a>   ";html+="</div>                                         ";html+="<div class='carts shopping'>                            ";html+="<div class='cartstext f16 shopping'>                    ";html+="您的购物车中暂无商品，赶快选择心爱的商品吧！      ";html+="</div>                                         ";html+="</div>                                         ";html+="<div class='cartsbottom shopping'>                      ";html+="<div class='cartsTotal shopping'>                       ";html+="<h3 class='fl shopping'>                                ";html+="<span class='shopping'>已选</span>                              ";html+="<strong class='CartNum shopping'>0</strong>             ";html+="<span class='shopping'>件</span>                                ";html+="</h3>                                          ";html+="<div class='FeeWrap fl shopping'>                       ";html+="<span class='ico shopping'>¥</span>                     ";html+="<strong class='prices shopping'>0.00</strong>           ";html+="</div>                                         ";html+="</div>                                         ";html+="<div class='Cashier btn_red gray shopping'>";html+="<div class='AccountGo f14 shopping'>                    ";html+="结算                                           ";html+="</div>                                         ";html+="</div>                                         ";html+="</div>";}
else{html+="<div class='cartlist shopping'>";html+="<div class='CartTop shopping'>";html+="<a class='CartBtn fr shopping' href='/letaozu/pay/usercart.aspx' title='全屏查看'>全屏查看</a>";html+="<div class='ChkBox fl shopping'>";html+="<input id='CartBox' type='checkbox' class='CartBox shopping' checked='checked' onclick=\"Letao.UI.ShoppingCartV3.CartParentClick('CartOrder input[type=checkbox]','CartBox')\" />";html+="</div>";html+="<label for='CartBox' class='fl shopping'>全选</label>";html+="</div>";for(var i=0;i<dr.Count;i++){if(dr[i]["HasStock"]==true){if(CartInfo.totalCount==0)
html+="<div class='CartMain shopping'>";}
html+=this.BuildProduct(dr[i],CartInfo,dtNoStock);}
if(CartInfo.totalCount>0)
html+="</div></div>";html+="<tfoot>";if(CartInfo.totalCount>0){var realTotalPrice=CartInfo.totalPrice;if(pdata!=null){realTotalPrice=realTotalPrice- pdata.PromotionPrice;}
html+="<div class='cartsbottom shopping'>";html+="<div class='cartsTotal shopping'>";html+="<h3 class='fl shopping'>";html+="<span class='shopping'>已选</span>";html+="<strong id='totalCount' class='CartNum shopping'>"+ CartInfo.totalCount+"</strong>";html+="<span class='shopping'>件</span>";html+="</h3>";html+="<div class='FeeWrap fl shopping'>";html+="<span class='ico shopping'>¥</span>";html+="<strong id='totalPrice' class='prices shopping'>"+ realTotalPrice.toFixed(2)+"</strong>";html+="<span class='shopping'>元</span>";html+="</div>";html+="</div>";html+="<div class='Cashier btn_red shopping' id='goBuy' onclick='Letao.UI.ShoppingCartV3.GoBuy();'>";html+="<div class='AccountGo f14 shopping'>";html+="结算";html+="</div>";html+="</div>";html+="</div>";}
if(dtNoStock.Rows.length!=0){var drNS=dtNoStock.Rows;html+="<div class='cartlist shopping'>"+"<div class='shopping' style=\"text-align:left;color:#999;border-bottom:1px solid #eee;padding:10px 0 5px\">"+"以下商品已售罄，暂无法购买"+"</div>";for(var i=0;i<drNS.length;i++){html+=this.BuildProduct(drNS[i],CartInfo);}
html+="</div>";}
html+="</div>";}
var returnObject={Count:CartInfo.totalCount+ CartInfo.noStockCount,Price:CartInfo.totalPrice,HTML:html};return returnObject;},BuildProduct:function(dr,CartInfo,dtNoStock){var pid,pname,pimage,psize,prsize,pcount,pprice,purl,pvprice;var parentid=null,parentsize=null,saletype=0,promoid=0;var html="",HasStock=dr["HasStock"];var subProduct,HasSubProduct=false;var ppromo,priceName="乐淘价";if(!HasStock&&typeof dtNoStock!="undefined"){dtNoStock.Rows.push(dr);return"";}
pid=dr["ProductID"].toString().substring(0,9);pname=dr["ProductName"].toString();pimage=dr["Image"].toString();psize=dr["ProductSize"].toString();prsize=dr["ProductID"].toString().substring(9,12);pcount=Math.floor(dr["ProductNum"]);pprice=parseFloat(dr["letao_price_discount"]);ppromo=parseInt(dr["letao_price_discount_type"]);purl=dr["StaticURL"].toString();pvprice=parseFloat(dr["letao_vprice"]);parentid=dr["ParentID"].toString();saletype=Math.floor(dr["SaleType"]);promoid=Math.floor(dr["PromoID"]);subProduct=dr["SubProduct"];productId=dr["ProductID"].toString();if(ppromo==100){priceName="黄金会员";}
if(ppromo==101){priceName="钻石会员";}
if(subProduct!=null&&subProduct.Rows.length>0)
HasSubProduct=true;if(parentid!=null&&parentid.length==12){parentsize=parentid.substring(9,12);parentid=parentid.substring(0,9);}
else{parentsize=null;}
html+="<div class='CartOrder shopping'>";html+="<div class='ChkBox fl shopping'>";html+="<input class='CartBox shopping' id='CartBox_"+ pid+"_"+ prsize+"_"+ pcount+"_"+ pprice.toFixed(2)+"' name='CartBoxs' value='CartBox_"+ pid+"_"+ prsize+"_"+ pcount+"_"+ pprice.toFixed(2)+"' type='checkbox'  checked='checked' onchange=\"Letao.UI.ShoppingCartV3.CarChildChange('CartOrder input[type=checkbox]:checked','CartOrder input[type=checkbox]','CartBox','CartBox_"+ pid+"_"+ prsize+"_"+ pcount+"_"+ pprice.toFixed(2)+"')\">";html+="</div>";html+="<div class='Item fl shopping'>";html+="<a class='Pic shopping' href='"+ purl+"' title='"+ pname+"' target='_blank'>";html+="<img height='40px' width='100%' src='"+ pimage+"'>";html+="</a>";html+="</div>";if(!HasStock){}
html+=" <div class='Sku fl shopping'><p class='shopping' title='"+ pname+"'>"+ pname+"</p></div>";if(HasStock&&saletype!=6){html+="  <div class='Amount fl shopping'>";html+="<a href=\"javascript:;\" "+"onclick=\"javascript:if($(this).prev('.tly_prodnum').html()=='1'){if(!confirm('您确定要将该件商品从购物车中删除吗？'))return false;};Letao.UI.ShoppingCartV3.SubstractProduct('"+ pid+"','"+ prsize+"',-1,'"+ parentid+"','"+ parentsize+"',"+ saletype+","+ promoid+").SetCartInner(function(){Letao.UI.ShoppingCartV3.SetCartCount('fnMyShopcart1','购物车','件','#f00',true);});\" "+"title=\""+(pcount==1?"删除此商品":"商品数量-1")+"\" class=\"icon-minus shopping\"></a>";html+="<span class='Quantity shopping'>"+ pcount+"</span>";html+="<a href=\"javascript:;\" "+"onclick=\"javascript:Letao.UI.ShoppingCartV3.AddProduct('"+ pid+"','"+ prsize+"',1,'"+ parentid+"','"+ parentsize+"',"+ saletype+","+ promoid+").SetCartInner(function(){Letao.UI.ShoppingCartV3.SetCartCount('fnMyShopcart1','购物车','件','#f00',true);},this);\" "+"class='icon-plus shopping'><s></s></a>";html+="</div>";}
else{html+="<div class='shopping' style='color:#999;float: left;margin: 0 auto;line-height: 60px;'>数量："+ pcount+"件</div>";}
html+="<div class='fl shopping'><strong class='Price shopping'>"+ pprice+"</strong></div>";html+="</div>";if(HasStock){CartInfo.totalCount+=pcount;CartInfo.totalPrice+=pprice*pcount;}
else{CartInfo.noStockCount+=pcount;}
if(HasSubProduct){for(var i=0,len=subProduct.Rows.length;i<len;i++){var drSub=subProduct.Rows[i];html+=arguments.callee(drSub,CartInfo,dtNoStock);}}
return html;},GetCart:function(func){this.Data=null;Letao.Business.ShoppingCart.Get(func);return this;},AddProduct:function(pid,size,count,parentid,parentsize,saletype,promoid,func){this.Data=null;Letao.Business.ShoppingCart.Add(pid,size,count,parentid,parentsize,saletype,promoid,func);return this;},SubstractProduct:function(pid,size,count,parentid,parentsize,saletype,promoid,func){this.Data=null;Letao.Business.ShoppingCart.Substract(pid,size,count,parentid,parentsize,saletype,promoid,func);return this;},RemoveProduct:function(pid,size,parentid,parentsize,saletype,promoid,func){this.Data=null;Letao.Business.ShoppingCart.Remove(pid,size,parentid,parentsize,saletype,promoid,func);return this;},ClearCart:function(func){this.Data=null;Letao.Business.ShoppingCart.Clear(func);return this;},CartObject:null,ShoppingCartModeWindow:function(data){var mw=Letao.UI.ModeWindow({ID:"letaoShoppingCart",Title:"我的购物车",Content:data,CSS:{width:"402px",border:"2px solid #d10042"},TitleCSS:{"background-color":"#f2f2f2",color:"#333","font-weight":"700"},ContentCSS:{width:"380px",padding:"5px 10px 15px"},CloseIcon:{ImageSrc:null},Backover:false,Drag:true});if(this.CartObject==null){this.CartObject=mw;var header=Letao.Page.HeaderFooter;$("#letaoShoppingCart").hover(function(){clearTimeout(header._CartTimer);header._CartTimer=null;},function(){header._CartTimer=setTimeout(function(){mw.Close();},200);});}
return mw;},MoveToCollect:function(obj,prodid,size){$.LT_AJAX("add_user_collection",prodid,function(al_return){if(al_return&&al_return[0]=="SUCCESS"){Letao.Base.Event().Set({pageX:obj.offset().left- 170,pageY:obj.offset().top- 10});Letao.UI.YellowFade.Show("收藏商品成功！",Letao.Base.Event,true,"left");setTimeout(function(){Letao.UI.YellowFade.Hide("right");},1600);}
else{if(al_return=="ERROR:用户未登录"){Letao.Base.Event().Set({pageX:obj.offset().left- 90,pageY:obj.offset().top- 10});Letao.UI.YellowFade.Show("请您登录后再收藏商品！",Letao.Base.Event,true,"left");setTimeout(function(){Letao.UI.YellowFade.Hide("right");},1600);}
else{alert(al_return);}}},"user_collect");},Show:function(func){var cartData=this.Data;if(cartData==null){cartData=Letao.Business.ShoppingCart.GetData();var loadingData="<div style=\"padding:30px;background:url(http://img.letao.com/letaozu/images/load/ajax-loader.gif) no-repeat center center\"></div>";Letao.UI.ShoppingCart.ShoppingCartModeWindow(loadingData).Show(showoption);if(cartData==null){var _accepttimes=500;var _timer=setInterval(function(){if(!_accepttimes--){clearInterval(_timer);return;}
cartData=Letao.Business.ShoppingCart.GetData();if(cartData!=null){clearInterval(_timer);var pData=Letao.Business.ShoppingCart.GetPromotionData();cartData=Letao.UI.ShoppingCartV3.Data=Letao.UI.ShoppingCartV3.SerializationData(cartData,pData);Letao.UI.ShoppingCartV3.CartObject.SetContent(cartData.HTML);if(typeof func=="function"){func();}
cartData=null;}},13);}}
else{showoption.reshow=true;Letao.UI.ShoppingCartV3.ShoppingCartModeWindow(cartData).Show(showoption);if(typeof func=="function"){func();}
cartData=null;}},ShowV3:function(func){var cartData=this.Data;if(cartData==null){cartData=Letao.Business.ShoppingCart.GetData();if(cartData==null){var _accepttimes=500;var _timer=setInterval(function(){if(!_accepttimes--){clearInterval(_timer);return;}
cartData=Letao.Business.ShoppingCart.GetData();if(cartData!=null){clearInterval(_timer);var pData=Letao.Business.ShoppingCart.GetPromotionData();cartData=Letao.UI.ShoppingCartV3.Data=Letao.UI.ShoppingCartV3.SerializationData(cartData,pData);$("#carttoolsNav").html(cartData.HTML);if(typeof func=="function"){func();}
cartData=null;}},13);}}
else{$("#carttoolsNav").html(cartData.HTML);cartData=null;}},SetCartInner:function(func,elem){var cartData=this.Data;if(cartData==null){cartData=Letao.Business.ShoppingCart.GetData();if(cartData==null){var _accepttimes=20;var _timer=setInterval(function(){if(!_accepttimes--){clearInterval(_timer);var alertData=Letao.Business.ShoppingCart.GetAlert();if(alertData!=""){if(typeof elem=="undefined")
alert(alertData);else{var obj=$(elem);if(typeof obj.offset=="undefined"||typeof obj.offset!="function"){alert(alertData);return;}
Letao.Base.Event().Set({pageX:obj.offset().left- 170,pageY:obj.offset().top- 15});Letao.UI.YellowFade.Show(alertData,Letao.Base.Event,true,"left");setTimeout(function(){Letao.UI.YellowFade.Hide("right");},1600);}}
return;}
cartData=Letao.Business.ShoppingCart.GetData();if(cartData!=null){clearInterval(_timer);var pData=Letao.Business.ShoppingCart.GetPromotionData();cartData=Letao.UI.ShoppingCartV3.Data=Letao.UI.ShoppingCartV3.SerializationData(cartData,pData);$("#carttoolsNav").html(cartData.HTML);if(typeof func=="function"){func();}
cartData=null;}},13);}}},SetCartCount:function(elemid,prevstring,sufixstring,color,ishaveparentheses){var Cart=Letao.UI.ShoppingCartV3;if(Cart.Data!=null&&typeof Cart.Data.Count!="undefined"&&$("#"+ elemid).length==1){if(typeof color!="undefined"){prevstring+="<i>";sufixstring="</i>"+ sufixstring;}
if(typeof ishaveparentheses=="boolean"&&ishaveparentheses){prevstring+="";sufixstring=""+ sufixstring;}
if($("#"+ elemid).parents(".manwill").length>0){$("#"+ elemid).html("<img src=\"/manwill/images/v2/goshopping.jpg\" alt=\"购物车\">");$("#lttopcart.manwill i:first").text(0).hide();}
else{$("#"+ elemid).html(prevstring+ Cart.Data.Count+ sufixstring);}
if(Cart.CartObject!=null){Cart.CartObject.SetContent(Cart.Data.HTML);}}
$("#cartNum").text(Cart.Data.Count);},GetCartCount:function(){if(Letao.UI.ShoppingCartV3.Data==null){return 0;}
var count=Letao.UI.ShoppingCartV3.Data.Count;if(typeof count=="undefined"||count==null){return 0;}
return count;},SetCartIds:function(data,func){this.Data=null;Letao.Business.ShoppingCart.SetCartIds(data,func);return this;},SaveSingleProIDS:function(data,func){this.Data=null;Letao.Business.ShoppingCart.SaveSingleProIDS(data,func);return this;},AddSingleProIds:function(data,func){this.Data=null;Letao.Business.ShoppingCart.AddSingleProIds(data,func);return this;},RemoveSingleProIds:function(data,func){this.Data=null;Letao.Business.ShoppingCart.RemoveSingleProIds(data,func);return this;},GoBuy:function(){Letao.UI.ShoppingCartV3.DataOp.Sumit();},SmallCart:[],SelShoppingCart:{CartInfo:{totalCount:0,totalPrice:0.00}},DataOp:{Add:function(data){if(data==undefined||data.length<=0)
Letao.UI.ShoppingCartV3.SmallCart.push(data);else{if($.inArray(data,Letao.UI.ShoppingCartV3.SmallCart)==-1){Letao.UI.ShoppingCartV3.SmallCart.push(data);}}},Remove:function(data){if(data==undefined||data.length<=0)return;else{if($.inArray(data,Letao.UI.ShoppingCartV3.SmallCart)!=-1){Letao.UI.ShoppingCartV3.SmallCart.splice($.inArray(data,Letao.UI.ShoppingCartV3.SmallCart),1);}}},Sumit:function(){var dataList=[],ids="";if(Letao.UI.ShoppingCartV3.SmallCart.length){$.each(Letao.UI.ShoppingCartV3.SmallCart,function(i,item){ids+=(item+",");});ids=ids.substring(0,ids.length- 1);Letao.UI.ShoppingCartV3.SetCartIds(ids,function(ret){if(ret[0]=="SUCCESS"){location.href='/letaozu/pay/create_order.aspx';}});}else{alert("请选择购物车中需要结算的商品!");return;}},SumitAddProIds:function(data){if(data.length<=0)return;else{Letao.UI.ShoppingCartV3.AddSingleProIds(data,function(ret){});}},SumitRemoveProIds:function(data){if(data.length<=0)return;else{Letao.UI.ShoppingCartV3.RemoveSingleProIds(data,function(ret){});}}},CartParentClick:function(sum,parent){if($("#"+ parent).is(':checked')==true){$("."+ sum).each(function(){$("."+ sum).attr("checked",true);});$("input[name='CartBoxs']:checked").each(function(){Letao.UI.ShoppingCartV3.DataOp.Add($(this).attr("value"));});}else{$("."+ sum).each(function(){$("."+ sum).attr("checked",false);});$("input[name='CartBoxs']").each(function(){Letao.UI.ShoppingCartV3.DataOp.Remove($(this).attr("value"));});}
Letao.UI.ShoppingCartV3.EavaluateTotal();},CarChildChange:function(e,sum,parent,tagValue){if($("."+ e).length==$("."+ sum).length){$("#"+ parent).attr("checked",true);}
else{$("#"+ parent).attr("checked",false);}
$("."+ sum).each(function(){if($(this).attr("checked")){Letao.UI.ShoppingCartV3.DataOp.Add($(this).val());Letao.UI.ShoppingCartV3.EavaluateTotal();}
else{Letao.UI.ShoppingCartV3.DataOp.Remove($(this).val());Letao.UI.ShoppingCartV3.EavaluateTotal();}});},EavaluateTotal:function(){Letao.UI.ShoppingCartV3.SelShoppingCart.CartInfo.totalCount=0;Letao.UI.ShoppingCartV3.SelShoppingCart.CartInfo.totalPrice=0.00;var proCount=0,proConst=0.00;if(Letao.UI.ShoppingCartV3.SmallCart.length){var tempData=Letao.UI.ShoppingCartV3.SmallCart.toString().split(',');$.each(tempData,function(i,item){var proTemp=item.toString().split('_');proCount+=(proTemp[3]>>0);proConst+=(proTemp[3]>>0)*parseFloat(proTemp[4]);});Letao.UI.ShoppingCartV3.SelShoppingCart.CartInfo.totalCount+=proCount;Letao.UI.ShoppingCartV3.SelShoppingCart.CartInfo.totalPrice+=proConst;}
$("#totalCount").html(Letao.UI.ShoppingCartV3.SelShoppingCart.CartInfo.totalCount);$("#totalPrice").html(Letao.UI.ShoppingCartV3.SelShoppingCart.CartInfo.totalPrice.toFixed(2));}},LazyLoad:{_initial:null,TYPE:{"Image":"Image","Flash":"Flash","Function":"Function"},LOADANIMATION:{FADEIN:"fadeIn"},fnConfig:(function(){var funcs={};var _add=function(id,func){funcs[id]=func;return this;};var _get=function(id){if(typeof funcs[id]=="undefined"){return null;}
return funcs[id];};var _remove=function(id){if(typeof funcs[id]=="undefined"){return false;}
delete funcs[id];return true;};return{add:_add,get:_get,remove:_remove};})(),init:function(){var lazyObjects={obj:null,length:0};var getLazyObjects=function(){return $("*[lazyload]");};var getImageLazyObjects=function(){return $("img[lazyload]");};var getConfigFunction=function(id){return Letao.UI.LazyLoad.fnConfig.get(id);};var initLazyObjects=function(jqObjects,isSetObj){var ret={};var _this,_lazy;jqObjects.each(function(i){_this=$(this);var lazystr=$(this).attr("lazyload");if(lazystr.indexOf(".swf")==-1){_lazy=splitLazyLoadStr(lazystr);ret[i]={entity:$(this),type:_lazy.type,lazyload:_lazy.lazyload};}
else{ret[i]={entity:$(this),type:Letao.UI.LazyLoad.TYPE.Flash,lazyload:$(this).attr("lazyload")};}
lazyObjects.length++;});if(typeof isSetObj=="boolean"&&isSetObj){setLazyObjects(ret);}
return ret;};var setLazyObjects=function(objs){lazyObjects.obj=objs;};var addLazyObjects=function(elem,type,lazyload){if(lazyObjects.obj==null){lazyObjects.obj={};}
handler=new Date().getTime()/ 1000;lazyObjects.obj[handler]={entity:elem,type:type,lazyload:lazyload};lazyObjects.length++;return;};var getWindow=function(){return{left:document.documentElement.scrollLeft||document.body.scrollLeft,top:document.documentElement.scrollTop||document.body.scrollTop,width:document.documentElement.clientWidth,height:document.documentElement.clientHeight}};var getObject=function(obj){return{left:$(obj).offset().left,top:$(obj).offset().top,width:$(obj).outerWidth(),height:$(obj).outerHeight()}};var splitLazyLoadStr=function(lazyloadstr){var splitIndex=lazyloadstr.indexOf(":");var lazyType=Letao.UI.LazyLoad.TYPE;if(splitIndex<=0){return{type:lazyType.Image,lazyload:lazyloadstr};}
var prev=lazyloadstr.slice(0,splitIndex++),next=typeof lazyType[prev]!="undefined"?lazyloadstr.slice(splitIndex):lazyloadstr;prev=next==lazyloadstr?"Image":prev;return{type:prev,lazyload:next};};var each=function(){var obj=null,entity=null,lazytype=null,lazyload=null;var lazyType=Letao.UI.LazyLoad.TYPE;var win=getWindow(),dom;for(i in lazyObjects.obj){obj=lazyObjects.obj[i];entity=obj.entity;if(entity.length==0){continue;}
dom=getObject(entity);if(isIntersect(dom,win)&&typeof lazyObjects.obj[i]!="undefined"){lazytype=obj.type;lazyload=obj.lazyload;if(lazytype==lazyType.Image){loadImage(entity,lazyload);delete lazyObjects.obj[i];lazyObjects.length--;continue;}
if(lazytype==lazyType.Function){loadFunction(entity,lazyload);delete lazyObjects.obj[i];lazyObjects.length--;continue;}
if(lazytype==lazyType.Flash){loadFlash(entity);delete lazyObjects.obj[i];lazyObjects.length--;continue;}}}};var loadImage=function(elem,src){if(typeof loadImage.applying=="undefined"){loadImage.applying=function(elem,imgsrc){var tagName=elem.attr("tagName")||elem.prop("tagName");if(tagName.toLowerCase()=="img"){elem.css("display","none").attr("src",imgsrc).show().removeAttr("lazyload");}
else{elem.css("background-image","url("+ imgsrc+")").fadeIn(800).removeAttr("lazyload");}
return;}}
var img=new Image();img.src=src;if(img.complete){loadImage.applying(elem,img.src);img=null;}
else{img.onload=function(){loadImage.applying(elem,img.src);img=null;}}};var loadFunction=function(elem,func){if(typeof func!="function"){func=getConfigFunction(func);}
if(!func){return;}
func.apply(elem);};var loadFlash=function(elem){var flasharr=[];flasharr.push('<embed align="middle" type="application/x-shockwave-flash" allowscriptaccess="always" quality="high" ');var width=elem.attr("width");var height=elem.attr("height");if(typeof width!='undefined'){flasharr.push(' width="'+ width+'" ');}
if(typeof height!='undefined'){flasharr.push(' height="'+ height+'" ');}
var flashsrc=elem.attr("lazyload");flasharr.push('src="'+ flashsrc+'" ');flasharr.push("/>");elem.replaceWith(flasharr.join(''));}
var isIntersect=function(rec1,rec2){var lp1=rec1.left+ rec1.width/2,lp2=rec2.left+ rec2.width/2,tp1=rec1.top+ rec1.height/2,tp2=rec2.top+ rec2.height/2,w1=(rec1.width+ rec2.width)/ 2,h1=(rec1.height+ rec2.height)/ 2;return Math.abs(lp1- lp2)<=w1&&Math.abs(tp1- tp2)<=h1;};return{getLazyObj:getLazyObjects,addLazyObj:addLazyObjects,initLazyObj:initLazyObjects,setLazyObj:setLazyObjects,isInter:isIntersect,each:each,loadImage:loadImage}},Run:function(objs,outer){if(this._initial==null){this._initial=this.init();}
var lz=this._initial;if(typeof objs=="undefined"||objs==null||typeof objs.length!="number"||typeof objs.size!="function"||typeof objs.each!="function"){lz.initLazyObj(lz.getLazyObj(),true);}
outer=outer||$(window);outer.scroll(function(){lz.each();});outer.resize(function(){lz.each();});lz.each();return this;},Add:function(elem,type,lazyload,func){if(this._initial==null){this._initial=this.init();}
var lz=this._initial;lz.addLazyObj(elem,type,lazyload);if(type==this.TYPE.Function){this.fnConfig.add(lazyload,func);}
lz.each();return this;}},SetClipboard:{copy:function(maintext){if(window.clipboardData){alert("复制成功！");return(window.clipboardData.setData("Text",maintext));}
else if(window.netscape){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect");}
catch(e){alert("被浏览器拒绝！\n请在浏览器地址栏输入'about:config'并回车\n然后将 'signed.applets.codebase_principal_support'设置为'true'");};var clip=Components.classes['@mozilla.org/widget/clipboard;1'].createInstance(Components.interfaces.nsIClipboard);if(!clip)return;var trans=Components.classes['@mozilla.org/widget/transferable;1'].createInstance(Components.interfaces.nsITransferable);if(!trans)return;trans.addDataFlavor('text/unicode');var str=new Object();var len=new Object();var str=Components.classes["@mozilla.org/supports-string;1"].createInstance(Components.interfaces.nsISupportsString);var copytext=maintext;str.data=copytext;trans.setTransferData("text/unicode",str,copytext.length*2);var clipid=Components.interfaces.nsIClipboard;if(!clip)return false;clip.setData(trans,null,clipid.kGlobalClipboard);}
alert("复制成功！");return false;},bindEvent:function(btnobj,iptobj){if(btnobj.length==0||iptobj.length==0){return false;}
btnobj.bind("click",function(){var content=iptobj.val();Letao.UI.SetClipboard.copy(content);});}},RollImage:function(){if(typeof this.RollImage._initialized_=="undefined"){var imageLoad=function(src,fn,context,args){var img=new Image();img.src=src;args.push(src);if(img.complete){fn.apply(context,args);}
else{img.onload=function(){fn.apply(context,args);};}};var createImage=function(src,id,style,type){if(typeof src!="string"){return null;}
type=type||"img";var ret;if(type=="img"){ret=$("<img>").attr("src",src);}
else{ret=$("<"+ type+">").css({"background-image":"url("+ src+")"});}
if(typeof id!="undefined"){ret.attr("id",id);}
if(typeof style!="undefined"){ret.css(style);}
return ret;};var defaultOption={images:[],parent:null,outer:null,indexer:null,onpreload:null,onload:null,isauto:false,cdnUrl:"http://img.letao.com",defaultImage:"/images/e.gif",preid:"",type:"img"};var F=function(){var args=arguments,op={},_this=this;if(args.length==1){op=args[0][0];}
op=$.extend({},defaultOption,op);for(var k in op){(function(key){var argName=k.substring(0,1).toUpperCase()+ k.substring(1);_this["set"+ argName]=function(){op[key]=arguments[0]||null;};_this["get"+ argName]=function(){return op[key];};})(k);}
this.__loaded={};this.__current={index:0,image:null};var timer={interval:null,stop:false,current:0,sec:5,callback:null};this.setTimer=function(fn,sec){timer.interval=setInterval(fn,sec);};this.stopTimer=function(){timer.stop=true;clearInterval(timer.interval);timer.interval=null;};this.isStop=function(){return timer.stop;};this.currentTimer=function(){var args=arguments;if(args.length==0){return timer.current;}
var cur=args[0];if(!isNaN(cur)){cur=parseInt(cur);timer.current=cur;return timer.current;}};this.timerSec=function(){var args=arguments;if(args.length==0){return timer.sec;}
var sec=args[0];if(!isNaN(sec)){sec=parseInt(sec);timer.sec=sec;return timer.sec;}};this.timerCallback=function(fn){if(typeof fn!="undefined"){timer.callback=fn;}
return timer.callback;};};F.prototype.load=function(index,fn){var loaded=this.__loaded;if(typeof loaded!="undefined"&&loaded.hasOwnProperty(index)&&(loaded[index].status=="loaded"||loaded[index].status=="indom")){fn.call(this,index,loaded[index]);return this;}
loaded[index]=loaded[index]||{};loaded[index].status="preload";var onpreload=this.getOnpreload(),onload=this.getOnload(),images=this.getImages(),src=images[index];src=src&&((src.length>0&&src[0]=="/")?this.getCdnUrl()+ src:src);onpreload&&onpreload.call(this);imageLoad.call(null,src,function(){var args=arguments,index=args[0],src=args[1],loaded=this.__loaded[index];if(loaded.status=="preload"){loaded.status="loaded";loaded.image=createImage(src,this.getPreid()+ index,{display:"none"},this.getType());}
fn.call(this,index,this.__loaded[index]);},this,[index]);return this;};F.prototype.bind=function(event,fnpre,fndone){var indexer=this.getIndexer(),_timer=null,_this=this;if(event=="hover"){indexer.hover(function(){var _self=this;_timer=setTimeout(function(){fnpre&&fnpre.call(_this,$(_self));var current=_this.__current,currentIndex=current.index,index=$(_self).attr("img_index");if(currentIndex!=index){_this.hide();current.index=index;_this.defaultLoad(index);}},200);},function(){var _self=this;fndone&&fndone.call(_this,$(_self));clearTimeout(_timer);_timer=null;});}
else{indexer.bind(event,function(){fnpre&&fnpre.call(_this,$(this));var current=_this.__current,currentIndex=current.index,index=$(this).attr("img_index");if(currentIndex!=index){_this.hide();current.index=index;_this.defaultLoad(index);}
fndone&&fndone.call(_this,$(this));});}
return this;};F.prototype.parent=function(event,fnpre,fndone){var parent=this.getParent(),_this=this;if(event=="hover"){parent.hover(function(){fnpre&&fnpre.call(_this,$(this));},function(){fndone&&fndone.call(_this,$(this));})}
else{parent.bind(event,function(){fnpre&&fnpre.call(_this,$(this));fndone&&fndone.call(_this,$(this));});}
return this;};F.prototype.hide=function(index){if(typeof index!="number"){var o=this.__current.image;if(o&&o.length!=0){o.stop(true,true).hide();}}
else{var loaded=this.__loaded;if(loaded.hasOwnProperty(index)){var loadedObject=loaded[index];if(loadedObject.status=="indom"&&loadedObject.image.length!=0){loadedObject.image.stop(true,true).hide();}}}
return this;};F.prototype.init=function(index,fn){index=index||0;this.defaultLoad(index);fn&&fn.call(this);return this;};F.prototype.defaultLoad=function(index){index=index||0
this.load(index,function(){var index=arguments[0],loaded=arguments[1],outer=this.getOuter(),status=loaded.status,image=loaded.image,current=this.__current;if(index==current.index&&typeof image!="undefined"){if(status=="loaded"){outer.append(image);loaded.status="indom";}
current.index=index;current.image=image;image.fadeIn(500);}});return this;};F.prototype.auto=function(sec,fn){sec=typeof sec=="undefined"?this.timerSec():this.timerSec(sec);fn=typeof fn=="undefined"?this.timerCallback():this.timerCallback(fn);var indexer=this.getIndexer(),group=[];indexer.each(function(i){$(this).data("autoIndex",i);group.push($(this).attr("img_index"));});var len=group.length,_this=this,cur=this.currentTimer();if(len>0){this.setTimer(function(){cur++;if(cur==len){cur=0;}
_this.currentTimer(cur);var index=group[cur],current=_this.__current,currentIndex=current.index;if(currentIndex!=index){_this.hide();current.index=index;_this.defaultLoad(index);}
fn&&fn.call(_this,group);},sec*1000);}};this.RollImage._initialized_=F;}
return new this.RollImage._initialized_(Array.prototype.slice.call(arguments,0));},Tab:function(){if(typeof this.Tab._initialized_=="undefined"){var defaultOption={indexer:{object:null,onfocus:"onfocus"},container:null};var binder=function(id,elem,event,iscache,islock,fn,callback){var _this=this;this.callback(id,callback);elem.bind(event,function(){var indexer=_this.getIndexer(),focus=_this.getFocus();indexer.removeClass(focus).eq(id).addClass(focus);if(iscache&&_this.store(id)){_this.show(id);return false;}
else{fn&&fn.call(_this);}});};var F=function(){var args=arguments,op={},_this=this;if(args.length==1){op=args[0][0];}
op=$.extend({},defaultOption,op);var indexObject=op.indexer.object,indexOnfocus=op.indexer.onfocus,container=op.container,lock=false;this.lock=function(){lock=true;};this.unlock=function(){lock=false;};this.islock=function(){return lock;};this.getIndexer=function(){return indexObject;};this.getFocus=function(){return indexOnfocus;};this.container=container;var callback={},store={};this.callback=function(id,fn){if(typeof fn=="undefined"){return callback[id]||null;}
return callback[id]=fn;};this.store=function(id,content){if(typeof content=="undefined"){return store[id]||null;}
return store[id]=content;};this.current={index:0,object:null};};F.prototype.index=function(id){var _this=this,obj=this.getIndexer().eq(id),focus=this.getFocus(),container=this.container,current=this.current;return{bind:function(){var args=Array.prototype.slice.call(arguments,0);args.unshift(id,obj);return binder.apply(_this,args);},init:function(){obj.addClass(focus);_this.store(id,container.children());current.index=id;current.object=_this.store(id);}};};F.prototype.setContainer=function(id,content){var jHTML=$(content);this.store(id,jHTML);this.container.append(jHTML);this.show(id);};F.prototype.show=function(id){var current=this.current;if(current.index==id&&current.object!=null){return this;}
var store=this.store(id);if(!store){return this;}
current.object&&current.object.stop(true,true).hide();current.index=id;current.object=store;store.show();};this.Tab._initialized_=F;}
return new this.Tab._initialized_(Array.prototype.slice.call(arguments,0));}}
Letao.Page.HeaderFooter={BindShoppingCart:function(id,showoption){var _this=this;_this._CartTimer=null;showoption=showoption||{};$("#"+ id).hover(function(){var _this=$(this);showoption.bindObject=_this;clearTimeout(_this._CartTimer);_this._CartTimer=null;var _left=_this.outerWidth()- 408,_top=_this.outerHeight();showoption.relativeTop=_top;showoption.relativeLeft=_left;Letao.UI.ShoppingCart.GetCart().Show(showoption);if($("#"+ id).hasClass("manwill")&&$("#"+ id).find("em:first i").text()>0){$("#"+ id).find("em:first i").show();}},function(){_this._CartTimer=setTimeout(function(){Letao.UI.ShoppingCart.CartObject.Close();},200);});},BindShoppingCartV3:function(id){Letao.UI.ShoppingCartV3.GetCart().ShowV3();},BindGoToPay:function(payid,cartid,showoption){$("#"+ payid).bind("click",function(){Letao.UI.ShoppingCart.GetCart(function(ret){var count=ret.Rows.length;if(count==0){showoption.bindObject=$("#"+ cartid);Letao.UI.ShoppingCart.GetCart().Show(showoption);}
else{window.location.href="/letaozu/pay/usercart.aspx";}});});},SmallMenu:(function(){function _CreateMenu(id,obj,options,css){if($("#"+ id).length!=0){return $("#"+ id);}
else{$("body").append($("<div>").attr("id",id).css({"position":"absolute","background-color":"#fff","padding":"6px","border":"1px solid #ddd","left":(obj.offset().left- 7)+"px","top":(obj.offset().top- 6)+"px","display":"none","z-index":"3"}));if(typeof css.width!="undefined"){$("#"+ id).css("width",css.width);}
else{$("#"+ id).css("width",obj.outerWidth()+"px");}
obj.clone().appendTo("<h6>").appendTo($("#"+ id));var _obj=null;var _innercontent="";var linkarr=[];_innercontent="<div style=\"padding:0\">";for(var i=0;i<options.length;i++){_obj=options[i];if(typeof _obj=="string"){_innercontent+="<p style=\"margin:2px 0 0 0;border-top:1px solid #eee;height:2px;overflow:hidden\"></p>";}
else{for(var j in _obj){linkarr.push(_obj[j]);}
_innercontent+="<p><a href=\""+ linkarr[0]+"\" title=\""+ linkarr[1]+"\" target=\""+ linkarr[2]+"\" style=\"line-height:20px;padding:0;text-decoration:none\">"+ linkarr[3]+"</a></p>";linkarr.length=0;}}
_innercontent+="</div>";$("#"+ id).append(_innercontent);return $("#"+ id);}}
function _ShowMenu(menuobj,obj){if(typeof obj!="undefined"){menuobj.css({"left":(obj.offset().left- 7)+"px","top":(obj.offset().top- 6)+"px"});}
menuobj.show();}
function _HideMenu(menuobj){menuobj.hide();}
return function(id,obj,options,css){var menuobj=null,_timer=null;obj.hover(function(){menuobj=_CreateMenu(id,obj,options,css);_ShowMenu(menuobj,obj);menuobj.hover(function(){clearTimeout(_timer);_timer=null;},function(){_HideMenu(menuobj);});},function(){_timer=setTimeout(function(){if(menuobj!=null){_HideMenu(menuobj);}},200);});}})(),SmallMenu2:(function(){function _CreateMenu(id,obj,fun){if($("#"+ id).length!=0){return $("#"+ id);}}
function _ShowMenu(menuobj,obj){obj.addClass("hover");if(menuobj.css("left")=="auto"){var $par=obj.parent(),topoff=obj.offset().top- $par.offset().top,leftoff=obj.offset().left- $par.offset().left;menuobj.css({top:obj.outerHeight()+ topoff- 1,left:obj.outerWidth()+ leftoff- menuobj.width()- 2});}
menuobj.show();}
function _HideMenu(menuobj,obj){obj.removeClass("hover");menuobj.hide();}
return function(id,obj,fun){var menuobj=null,_timer=null;obj.hover(function(){menuobj=_CreateMenu(id,obj,fun);if(typeof fun=="function"){fun.apply(menuobj);fun=null;}
_ShowMenu(menuobj,obj);menuobj.hover(function(){clearTimeout(_timer);_timer=null;},function(){_HideMenu(menuobj,obj);});},function(){_timer=setTimeout(function(){if(menuobj!=null){_HideMenu(menuobj,obj);}},50);});}})(),AutoComplete:autoComplete,SearchBar:(function(){function _SearchKeyword(keyword){if(typeof keyword!="string"){return false;}
keyword=keyword.trim();if(keyword==""||keyword=="请您输入想要搜索的关键词"){Letao.UI.YellowFade.Show("请您输入想要搜索的关键词",Letao.Base.Event,false,"left");setTimeout(function(){Letao.UI.YellowFade.Hide("up");},1200);return false;}
keyword=keyword.replace("'"," ");keyword=keyword.replace('"',' ');keyword=keyword.replace("script"," ");keyword=keyword.replace("?"," ");keyword=keyword.replace("\?"," ");keyword=keyword.replace("\/"," ");keyword=keyword.replace("\\"," ");keyword=keyword.replace("<","&lt;");keyword=keyword.replace(">","&gt;");keyword=encodeURIComponent(keyword);window.location.href="/s~"+ keyword+ _SetTimeStamp();}
function _SetTimeStamp(){var t=new Date();var year=t.getUTCFullYear()+"";var month=t.getUTCMonth()+ 1<10?"0"+(t.getUTCMonth()+ 1):(t.getUTCMonth()+ 1)+"";var day=t.getUTCDate()<10?"0"+ t.getUTCDate():t.getUTCDate()+"";var hour=t.getUTCHours()<10?"0"+ t.getUTCHours():t.getUTCHours()+"";var minute=t.getUTCMinutes()<10?"0"+ t.getUTCMinutes():t.getUTCMinutes()+"";var ts="?ts="+ year+ month+ day+ hour+ minute;return ts;}
return function(inputobject,buttonobject,defaultkeyword,userkeyword){defaultkeyword=defaultkeyword||"请您输入想要搜索的关键词";if(typeof userkeyword=="string"&&userkeyword.trim()!=""){inputobject.val(userkeyword).addClass("usersearch");}
else{inputobject.val(defaultkeyword);}
inputobject.focus(function(){if($(this).val()==defaultkeyword){$(this).val("").addClass("usersearch");}});inputobject.blur(function(){if($(this).val()==""){$(this).val(defaultkeyword).removeClass("usersearch");}});inputobject.keypress(function(e){e=e||event;if(e.keyCode==13){_SearchKeyword($(this).val());return false;}});buttonobject.bind("click",function(){_SearchKeyword(inputobject.val());});return{SearchKeyword:_SearchKeyword};}})(),AddFavorite:function(elem,fn){var webkit=Letao.Business.WebToolkit;if(webkit.CheckBrowser()){elem.bind("click",function(){webkit.AddFavorite("乐淘网上鞋城 - 买鞋子，上乐淘","http://www.letao.com/");webkit.Close();if(typeof fn=="function"){fn.call();}});}
else{$("<span>按<strong>Ctrl + D</strong>,</span>").prependTo(elem.parent());elem.remove();}},BindNavLink2:function(hoverObject,hasLink,target){var menudata=this.BindNavLink2.SubMenuData,data=menudata||{},HtmlData={},current=null;hoverObject.hover(function(){var _this=$(this);var submenu_id=_this.attr("submenu2_id");clearTimer();clearBar(submenu_id,_this);current=_this.children("a");addCurrentClass(current);if(typeof submenu_id!="undefined"){if(typeof menudata=="undefined"){SubBar(submenu_id,_this).html("<div style=\"height:200px;background:#fff url(http://img.letao.com/letaozu/images/load/ajax-loader.gif) no-repeat 50% 50%\"></div>");ShowBar(submenu_id,_this);var callback=function(res){if(res==null)
return;if(res[0]=="SUCCESS"){data=menudata=$.parseJSON("{"+ res[1]+"}");setHtml(submenu_id,_this);}};$.LT_AJAX("get_menudata",null,callback,"user_site_topmenu");}
else{show(submenu_id,_this);}}},function(){var _this=$(this);var submenu_id=_this.attr("submenuid");timer=setTimeout(function(){clearBar(submenu_id,_this);},200);});var show=function(id,obj){setHtml(id,obj);ShowBar(id,obj);};var setHtml=function(id,obj){var _html=HtmlData[id]||BuildHtml(id,data[id]);if(_html){obj.hasClass("sub")?null:obj.find("a").addClass("subhover").addClass("sub").removeClass("hover");SubBar(id,obj).html(_html);}};var addCurrentClass=function(cur){cur.hasClass("sub")?cur.addClass("subhover"):cur.addClass("hover");};var removeCurrentClass=function(cur){if(cur==null)return;cur.hasClass("subhover")?cur.removeClass("subhover"):cur.removeClass("hover");};var timer=null;var SubBar=function(id,obj){var subid="sub_"+ id;if($("#"+ subid).length==0&&typeof obj!="undefined"){obj.closest("div").append($("<div>").attr({id:subid}).addClass("ddl"));$("#"+ subid).hover(function(){clearTimer();},function(){clearBar(id,obj);});}
return $("#"+ subid);};var ShowBar=function(id,obj){var subid="sub_"+ id,subobj=$("#"+ subid);if(subobj.css("left")=="0px"||subobj.css("left")=="auto"){var parent=obj.closest("div"),oleft=obj.offset().left,pleft=parent.offset().left,offset=oleft+ subobj.outerWidth()-(pleft+ parent.outerWidth());if(offset<0)offset=0;subobj.css({left:oleft- pleft- offset});}
var h1=subobj.find(".listinfo").height(),h2=subobj.find(".brandinfo").height();if(h1<h2){subobj.find(".listinfo").css("height",h2);}
subobj.show();};var clearTimer=function(){window.clearTimeout(timer);timer=null;};var clearBar=function(id,obj){obj.closest("div").find(".ddl").hide();removeCurrentClass(current);};var BuildHtml=function(id,data){if(typeof data=="undefined"||data==null)
return"";var ltid,i,j,len;var _html="";if(Object.prototype.toString.apply(data.list)==="[object Array]"&&data.list.length>0){_html+="<div class=\"listinfo\">"
for(i=0,len=data.list.length;i<len;i++){var _list=data.list[i];var _list0=_list[0];_html+="<dl";if(i==len- 1&&!hasLink){_html+=" style=\"border:0 none\"";}
_html+=">";ltid="lt_submenu_"+ id+"_list_"+ i;_html+="<dt>";_html+=_list0[1];_html+=":</dt><dd>";for(j=1;j<_list.length;j++){var __list=_list[j];_html+=BuildALink(ltid+"_"+(j- 1),__list[0],__list[1],__list[1],1,ltid+"_"+ __list[2]);}
_html+="</dd></dl>";}
if(hasLink){}
_html+="<br class=\"clear\">";_html+="</div>";}
HtmlData[id]=_html;return _html;};var BuildALink=function(ltid,url,title,txt,lttype,ltlinkid){var aLink="<a lt_stat_id=\""+ ltid+"\"";if(typeof lttype!="undefined"){aLink+=" lt_stat_type=\""+ lttype+"\"";}
if(typeof ltlinkid!="undefined"){aLink+=" lt_stat_linkid=\""+ ltlinkid+"\"";}
aLink+=" href=\""+ url+"\" title=\""+ title+"\" target=\""+ target+"\">"+ txt+"</a>";return aLink;};var BuildImg=function(url,txt){var CDNUrl="http://img.letao.com";var img="<img src=\""+ CDNUrl+ url+"\" alt=\""+ txt+"\" />";return img;};},CoupanAlert:function(){if(Letao.UI.ModeWindow){var windowContent="<p style=\"padding:24px 12px 0;line-height:20px;letter-spacing:0.1em;position:relative\">"+"恭喜！您获得<i class=\"red\">1元</i>购买<i class=\"red\">50元</i>乐淘优惠券特权&nbsp;&nbsp;"+"<a href=\"/shoe-letao-999888888\" target=\"_blank\" onclick=\"$('#letaoNewComerCoupanAlert').hide();\">立即去抢！</a>"+"<span onclick=\"$('#letaoNewComerCoupanAlert').hide();$.LT_AJAX('give_up_get_coupan',null,function(){},'user_coupan');\" style=\"display:block;position:absolute;top:12px;right:8px;width:8px;height:7px;background:url(http://img.letao.com/letaozu/images/ui/yellowalert_close.gif) no-repeat 0 0;cursor:pointer\"></span>"+"</p>";var mw=Letao.UI.ModeWindow({ID:"letaoNewComerCoupanAlert",Title:"",Content:windowContent,CSS:{"border":"0","width":"199px","background":"transparent"},TitleCSS:{"display":"none"},ContentCSS:{"background":"url(http://img.letao.com/letaozu/images/ui/yellowalert.gif) no-repeat 0 0","width":"199px","height":"84px","padding":"0"},CloseIcon:false,Backover:false,Drag:false});mw.Show({position:"bindto",relativeTop:15,relativeLeft:-80,bindObject:$("#lnkRegist")});}},BindLogo:function(elem){var _this=this;if(typeof _this.BindLogo.isRun=="undefined"){_this.BindLogo.isRun=true;}
elem.hover(function(){if(_this.BindLogo.isRun)
elem.css("background-position","right 0");},function(){if(_this.BindLogo.isRun)
elem.css("background-position","-1000px -1000px");});},Share:(function(){var _init=function(){this.url="";this.image="http://img.letao.com/letaozu/images/3rd/share_8365.gif";this.title="";this.content="";this.source="";this.addon="?source=";};_init.prototype.Encode=function(){if(this.url.indexOf("?")>=0){this.addon="&source=";}
var url=encodeURIComponent(this.url),image=encodeURIComponent(this.image),title=encodeURIComponent(this.title),content=encodeURIComponent(this.content),source=encodeURIComponent(this.source),addon=encodeURIComponent(this.addon);return{url:url,image:image,title:title,content:content,source:source,addon:addon};};_init.prototype.To=function(id,source){source=source||this.source;var normal=this,encode=this.Encode(),url=source==""?encode.url:encode.url+ encode.addon+ source;if(id=="tsina"){window.open("http://v.t.sina.com.cn/share/share.php?url="+ url+"&appkey=2674876054&title="+ encode.content+"&pic="+ encode.image,"_blank","width=615,height=800");return;}
if(id=="renren"){var _content=this.content.replace("@乐淘网上鞋城","@乐淘");_content=encodeURIComponent(_content);window.open("http://www.connect.renren.com/share/sharer?url="+ url+"&title="+ _content,"_blank","_blank","width=615,height=505");return;}
if(id=="kaixin"){window.open("http://www.kaixin001.com/repaste/share.php?rtitle="+ encode.content+"&rcontent="+ encode.content+"&rurl="+ url);return;}
if(id=="tqq"){window.open("http://v.t.qq.com/share/share.php?source=a207af85abfc489a835c773edc260832&site=http://www.letao.com&title="+ encode.content+"&pic="+ encode.image+"&url="+ url,"_blank","width=600,height:500");return;}
if(id=="tsohu"){var _content=this.content.replace("@乐淘网上鞋城","@乐淘鞋城");_content=encodeURIComponent(_content);window.open("http://t.sohu.com/third/post.jsp?url="+ url+"&title="+ _content+"&content=utf-8&pic="+ encode.image,"_blank","width=615,height=505");return;}
if(id=="qzone"){window.open("http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url="+ url+"&title="+ encode.content+"&desc="+ encode.content+"&pics="+ encode.image,"_blank","width=615,height=505");return;}
if(id=="qpengyou"){window.open("http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url="+ url+"&to=pengyou&title="+ encode.content+"&desc="+ encode.content+"&pics="+ encode.image,"_blank","width=615,height=505");return;}
if(id=="wangyi163"){var _source=encodeURIComponent("乐淘网上鞋城");window.open("http://t.163.com/article/user/checkLogin.do?link="+ url+"&source="+ _source+"&info="+ encode.content+ url+"&images="+ encode.image+"&togImg=true","_blank","height=330,width=550");return;}};return function(){return new _init();};})(),Message:(function(){var SetNew=function(obj){obj.append($("<b>").addClass("new"));};var MsgWM=function(){if($("#MsgShow").length==0){$("<div>").attr({id:"MsgShow"}).prependTo($("#ltmenu"));}
return $("#MsgShow");};var GetMsg=function(obj){var callback=function(res){if(res==null||res[0]!="SUCCESS"){return;}
else{var wm=MsgWM();wm.html(res[1]).fadeIn();SetNew(obj);$("#ddl_Message a").each(function(n){$(this).find("b").html("("+ res[n+ 2]+")");});wm.find(".msgbody b").bind("click",function(){wm.fadeOut();});}};$.LT_AJAX("get_message",null,callback,"user_site_topmenu");};return function(obj){if(typeof obj=="undefined"||obj.length==0){return;}
var timer=setTimeout(function(){GetMsg(obj);},2000);}})(),RollImage:(function(){var Auto=function(_timestep){var timestep=_timestep||7;this.auto(timestep,function(group){var cur=this.currentTimer(),index=group[cur],indexer=this.getIndexer();if(this.getBackground&&this.getBackground().length>0){var bg=this.getBackground()[cur];if(bg){if(bg.indexOf('.')>=0)
{this.getParent().css({"background-image":"url('"+ bg+"')","background-color":"transparent"});}
else{this.getParent().css({"background-color":bg,"background-image":"none"});}}
else{this.getParent().css({"background-color":"transparent","background-image":"none"});}};var curObj=indexer.removeClass("imgfocus").eq(index).addClass("imgfocus");this.getOuter().attr("href",curObj.attr("href"));});};return{Run:function(_images,_parent,_outer,_indexer,_preid,_timestep,_type,_background){var ri=Letao.UI.RollImage({images:_images,parent:_parent,outer:_outer,indexer:_indexer,preid:_preid,type:_type||"img",background:_background});ri.init(0,function(){var firstObject=this.getIndexer().eq(0);firstObject.addClass("imgfocus");this.getOuter().attr("href",firstObject.attr("href"));if(this.getBackground&&this.getBackground().length>0){var bg=this.getBackground()[0];if(bg){if(bg.indexOf('.')>=0)
{this.getParent().css({"background-image":"url('"+ bg+"')","background-color":"transparent"});}
else{this.getParent().css({"background-color":bg,"background-image":"none"});}}
else{this.getParent().css({"background-color":"transparent","background-image":"none"});}};}).bind("hover",function(elem){if(this.getBackground&&this.getBackground().length>0){var bg=this.getBackground()[elem.data("autoIndex")];if(bg){if(bg.indexOf('.')>=0)
{this.getParent().css({"background-image":"url('"+ bg+"')","background-color":"transparent"});}
else{this.getParent().css({"background-color":bg,"background-image":"none"});}}
else{this.getParent().css({"background-color":"transparent","background-image":"none"});}}
elem.parent().find("a").removeClass("imgfocus");elem.addClass("imgfocus");this.getOuter().attr("href",elem.attr("href"));this.currentTimer(elem.data("autoIndex"));}).parent("hover",function(){this.stopTimer();},function(){Auto.call(this,_timestep);});Auto.call(ri,_timestep);}}})(),Tab:(function(){var Init=function(ws,data){if(!data||!$.isArray(data)){return false;}
var _this=this;for(var i=0;i<data.length;i++){(function(){var n=i,_data=data[n];_this.index(n).bind("mouseover",true,false,function(){$.LT_AJAX(_data[0],_data[1],this.callback(n),ws,this);},function(ret){if(!ret||ret[0]!="SUCCESS"){return;}
this.setContainer(n,ret[1]);});if(typeof _data[2]!="undefined"){_this.index(n).init();}})();}};return{Run:function(_indexer,_container,_focusclass,ws,data){var tab=Letao.UI.Tab({indexer:{object:_indexer,onfocus:_focusclass},container:_container});Init.call(tab,ws,data);}}})(),BindVip:function(id){if($("#"+ id).length==0)
return false;var vip=$("#"+ id),timer=null,vipinfo=$("#topmenu_vipinfo");vip.hover(function(){clearTimeout(timer);timer=null;vipinfo.show();},function(){timer=setTimeout(function(){vipinfo.hide();},200);});vipinfo.hover(function(){clearTimeout(timer);timer=null;},function(){timer=setTimeout(function(){vipinfo.hide();},200);});},BindOwnBrandCategory:(function(){var minLeft=20,minTop=10,maxTop=185,minRight=20,minWidth=990;var cate,cover,_timer=null;var OwnBrand=["index_chance","index_imosii"];var resize=function(){var winWidth=$(window).width(),_w=100,_lw=(winWidth- minWidth)/ 2;for(var o in OwnBrand){if(lt_page_id==OwnBrand[o]){_w=125;break;}}
var _top=maxTop,_left=minLeft;if(_lw>=_w+ minRight){_left=_lw- _w- minRight;}
cate.css({left:_left});};var scroll=function(){var scrollTop=$(document).scrollTop(),_top=maxTop;if(scrollTop>=maxTop- minTop){_top=scrollTop+ minTop;}
cate.css({top:_top});};return{run:function(id){if($("#"+ id).length==0)
return false;cate=$("#"+ id);cover=cate.find(".cover");cate.find("h2 i").click(function(){var contain=cate.find("div:first"),cssName=cate.attr("brand")+"min";contain.toggleClass(cssName);});var onhover=function(){clearTimeout(_timer);_timer=null;};var onblur=function(){_timer=setTimeout(function(){cover.hide();cate.find(".cate").hide();},200);};cate.find("a[subid]").hover(function(){var _this=$(this),subid=_this.attr("subid"),parentTop=cate.offset().top,_top=_this.offset().top,_height=_this.outerHeight(),subdiv=cate.find("div[subid='"+ subid+"']"),subHeight=subdiv.outerHeight(),covTop=_top- parentTop- 1,subTop=covTop-(subHeight- _height- 2);cate.find(".cate").hide();onhover();cover.html("").append(_this.clone()).css({top:covTop}).show();subdiv.css({top:subTop}).show();if(_this.parent().hasClass("pic")){cover.addClass("pic");}
else{cover.removeClass("pic");}},onblur);cover.hover(onhover,onblur);cate.find(".cate").each(function(){$(this).hover(onhover,onblur);});$(window).resize(resize);resize();$(window).scroll(scroll);scroll();},set:function(opt){maxTop=opt.maxTop;minRight=opt.minRight;resize();scroll();}}})()}
Letao._INSTALL();})();$(function(){try{document.execCommand("BackgroundImageCache",false,true);}catch(e){}
Letao.Page.HeaderFooter.BindLogo($("#ltlogo"));Letao.Page.HeaderFooter.BindNavLink2($("#lttopbar2 li"),true,"_blank");Letao.Page.HeaderFooter.BindNavLink2($("#cctopbar li"),false,"_self");Letao.Page.HeaderFooter.BindVip("lt_top_vip");Letao.Page.HeaderFooter.BindOwnBrandCategory.run("obCategory");Letao.Page.HeaderFooter.BindShoppingCartV3("carttoolsNav");var LT_DEFAULT_SEARCH_KEYWORD=typeof _DEFAULT_SEARCH_KEYWORD=="undefined"?"":_DEFAULT_SEARCH_KEYWORD;var LT_USER_SEARCH_KEYWORD=typeof _USER_SEARCH_KEYWORD=="undefined"?"":_USER_SEARCH_KEYWORD;var _searchEng=Letao.Page.HeaderFooter.SearchBar($("#iptSearch"),$("#btnSearch"),LT_DEFAULT_SEARCH_KEYWORD,LT_USER_SEARCH_KEYWORD);var ac=Letao.Page.HeaderFooter.AutoComplete($("#iptSearch"));ac.bindFocusEvent(function(){var keyword=this._focusData;_searchEng.SearchKeyword(keyword);});ac.run();Letao.UI.LazyLoad.Run();var myletaoMenuInner=[];myletaoMenuInner.push("line");myletaoMenuInner.push({href:"/letaozu/MyLetao/OrderList.aspx",title:"我的订单",target:"_self",text:"我的订单"});myletaoMenuInner.push({href:"/letaozu/MyLetao/CommentList.aspx",title:"我的评价",target:"_self",text:"我的评价"});myletaoMenuInner.push({href:"/letaozu/MyLetao/MyComment.aspx",title:"我的咨询",target:"_self",text:"我的咨询"});myletaoMenuInner.push("line");myletaoMenuInner.push({href:"/letaozu/MyLetao/MyCollection.aspx",title:"我的收藏",target:"_self",text:"我的收藏"});myletaoMenuInner.push({href:"/letaozu/MyLetao/MyCoupan.aspx",title:"我的优惠券",target:"_self",text:"我的优惠券"});myletaoMenuInner.push("line");myletaoMenuInner.push({href:"/letaozu/MyLetao/MyAddress.aspx",title:"收货地址",target:"_self",text:"收货地址"});myletaoMenuInner.push({href:"/letaozu/MyLetao/ChangePwd.aspx",title:"修改密码",target:"_self",text:"修改密码"});Letao.Page.HeaderFooter.SmallMenu("MyLetao_Menu_DDL",$("#fnMyLetao"),myletaoMenuInner,{width:"60px"});var helpMenuInner=[];helpMenuInner.push("line");helpMenuInner.push({herf:"/letaozu/help/helpindex.aspx",title:"帮助中心",target:"_blank",text:"帮助中心"});helpMenuInner.push({herf:"/letaozu/help/help.aspx?id=1010#3",title:"留言咨询",target:"_blank",text:"留言咨询"});helpMenuInner.push("line");helpMenuInner.push({herf:"/letaozu/help/help.aspx?id=1018",title:"售后服务",target:"_blank",text:"售后服务"});Letao.Page.HeaderFooter.SmallMenu("Help_Menu_DDL",$("#fnHelper"),helpMenuInner,{width:"60px"});Letao.Page.HeaderFooter.SmallMenu2("ddl_MyLetao",$("#fnMyLetao2"),function(){var _this=this;var callback=function(res){_this.find(".loading").remove();if(res==null||res[0]!="SUCCESS"){return;}
$(res[1]).insertAfter(_this.find("em"));};$.LT_AJAX("get_lastorder",null,callback,"user_site_topmenu");});Letao.Page.HeaderFooter.SmallMenu2("ddl_History",$("#fnHistory2"),function(){var _this=this;var callback=function(res){if(res==null||res[0]!="SUCCESS"){_this.html("<div style=\"padding:30px 0;color:#1b1b1b;font-size:14px;text-align:center\">您还没有任何浏览记录！</div>");return;}
_this.html(res[1]);};$.LT_AJAX("get_history",null,callback,"user_site_topmenu");});Letao.Page.HeaderFooter.SmallMenu2("ddl_Message",$("#fnMessage2"));Letao.Page.HeaderFooter.AddFavorite($("#collectletao"),function(){$(".lttopcollect").animate({height:0},function(){$(".lttopcollect").remove();Letao.Business.WebToolkit.Off();});});Letao.Page.HeaderFooter.Message($("#fnMessage2"));if($(".lttopcollect").length!=0){$(".lttopcollect .close").click(function(){$(".lttopcollect").animate({height:0},function(){$(".lttopcollect").remove();Letao.Business.WebToolkit.Close();});});$("#nocollectletao").click(function(){$(".lttopcollect").animate({height:0},function(){$(".lttopcollect").remove();Letao.Business.WebToolkit.Off();});});}
$("#otherbrand").delegate("a[cmsid]","click",function(){var _this=$(this);if(_this.hasClass("cur"))
return;var cmsid=_this.attr("cmsid");var callback=function(res){if(res==null||res[0]!="SUCCESS"){return;}
else{$("#otherbrand a.cur").removeClass("cur");_this.addClass("cur");$("#otherbrand div.contain").html(res[1]);$("#otherbrand div.contain img").each(function(){var $img=$(this);Letao.UI.LazyLoad.Add($img,"Image",$img.attr("lazyload"));});}};$.LT_AJAX("get_brand_content",cmsid,callback,"user_ownbrand_index");});$("#ownbrandlist").delegate(".ownbrand-left>img[customid]","click",function(){var _this=$(this);var customid=_this.attr("customid");var ImgUrl=_this.attr("imgurl");if(_this.hasClass("cur")){return;}
else{$("#ownbrandlist .ownbrand-left img[customid]").each(function(){var ImgCurrent=$(this);var ImgCurrentSrc=ImgCurrent.attr("src");var ImgCurrentSmallUrl=ImgCurrent.attr("imgurl_small");var ImgCurrentUrl=_this.attr("imgurl");ImgCurrent.attr("src",ImgCurrentSmallUrl).removeClass("cur");});_this.attr("src",ImgUrl).addClass("cur");}
var callback=function(res){if(res==null||res[0]!="SUCCESS"){return;}
$("#ownbrandlist .ownbrand-right").hide().html(res[1]).fadeIn();$("#ownbrandlist .ownbrand-right img").each(function(){var $img=$(this);Letao.UI.LazyLoad.Add($img,"Image",$img.attr("lazyload"));});};$.LT_AJAX("getownbrandcontent",customid,callback,"user_ownbrand_index");});if($("#lttopcart").find("em:first i").text()>0){$("#lttopcart").find("em:first i").show();};$("#ltfootermenu").delegate("a","mouseover",function(){var _this=$(this),index=_this.index();if(_this.hasClass("onchos")){return;}
_this.parent().find(".onchos").removeClass("onchos");_this.addClass("onchos");$("#ltfooterouter div").hide();$("#ltfooterouter div").eq(index).show();});$(".lttopmenu .ownbrand li:not(.cur)").hover(function(){var _this=$(this);if(_this.hasClass("letao")){_this.addClass("letaohover");}
else{_this.addClass("hover");}},function(){var _this=$(this);if(_this.hasClass("letao")){_this.removeClass("letaohover");}
else{_this.removeClass("hover");}});});