var t=n=0,count;$(function(){var province='';$("#Express").hover(function(){$(this).find(".EDiv").show();},function(){$(this).find(".EDiv").hide();});if($.cookie("ckProv")==null){if(typeof(returnCitySN)!="undefined"&&returnCitySN!=''&&returnCitySN!=null){if(returnCitySN["cname"].indexOf('省')>0){province=returnCitySN["cname"].substring(0,returnCitySN["cname"].lastIndexOf('省'));}else if(returnCitySN["cname"].indexOf('市')>0){province=returnCitySN["cname"].substring(0,returnCitySN["cname"].lastIndexOf('市'));}else if(returnCitySN["cname"].indexOf('特别')>0){province=returnCitySN["cname"].substring(0,returnCitySN["cname"].lastIndexOf('特'));}else{province=returnCitySN["cname"].substring(0,returnCitySN["cname"].lastIndexOf('自'));}
$("#prov").text(province);}else{$("#prov").text("广东");}}else{$("#prov").text($.cookie("ckProv"));}
$("#Express a").each(function(){if($(this).text()==$("#prov").text())
$(this).addClass("sign");});$("#Express a:not(.sign)").hover(function(){$(this).addClass("hover");},function(){$(this).removeClass("hover");});$("#banner_list li").soChange({thumbObj:"#banner_num li",botPrev:"#banner .left",botNext:"#banner .right",thumbNowClass:"on"});$(".caricon").click(function(){$("input[name='CartBoxs']:checked").each(function(){Letao.UI.ShoppingCartV3.DataOp.Add($(this).attr("value"));});if($(".cart-wrap").css("right")=="-310px"){$(".cart-wrap").animate({right:"0px"});$(".rightFixed").animate({right:"310px"});var cartBarHeight=parseFloat($(window).height()- $(".cartsbottom").height()- $(".CartTop").height());$(".CartMain").css("height",cartBarHeight+"px");$(".CartMain").slimScroll({color:'#000',size:'10px',height:$(".CartMain").height()- 10,alwaysVisible:true,railClass:'slimScrollRail shopping',barClass:'slimScrollBar shopping',wrapperClass:'slimScrollDiv shopping',borderRadius:'5px',railBorderRadius:'5px'});}
else{$(".cart-wrap").animate({right:"-310px"});$(".rightFixed").animate({right:"0px"});}});$("body").bind("click",function(e){var thisTarget=e.target||window.event.target||arguments[0].target;if(thisTarget.className.indexOf("shopping")<0){$(".cart-wrap").animate({right:"-310px"});$(".rightFixed").animate({right:"0px"});}});$("#collect").hover(function(){$(this).addClass("hover");},function(){$(this).removeClass("hover");});$("#collect").click(function(){var url='http://www.letao.com';var title="乐淘网";AddFavorites(title,url);});$(".cataline").hover(function(){$(this).addClass("hover");$(this).find(".RightCata").show();},function(){$(this).removeClass("hover");$(this).find(".RightCata").hide();});$("#qrLetao").hover(function(){$("#qrLetao .qrcode").show();$(this).addClass("hover");},function(){$("#qrLetao .qrcode").hide();$(this).removeClass("hover");});$("#MyLetao").hover(function(){$(this).addClass("hover");$("#MyLetao .cusinfos").show();},function(){$(this).removeClass("hover");$("#MyLetao .cusinfos").hide();});$("#MyMessage").hover(function(){$(this).addClass("hover");$("#MyMessage .LetaoMess").show();},function(){$(this).removeClass("hover");$("#MyMessage .LetaoMess").hide();});$(".AD .close").click(function(){$(".AD").hide();});$(".AD .close").hover(function(){$(this).addClass("hover");},function(){$(this).removeClass("hover");});$(".topbttom .center div:not(.hover)").hover(function(){$(this).addClass("hover");},function(){$(this).removeClass("hover");});$(".t_nav_right .tab li").hover(function(){$(this).addClass("hover");},function(){$(this).removeClass("hover");});$('.recommend').myTab({operate:'mouseover',time:3000,auto:false,delayTime:0});$(".screenBox .screen:last").addClass("bbnone");var i=0;$("#ul2 li").each(function(){if(i>6){$("#ul2 #Li_"+ i).addClass("hidden");}
i++;});$("#sul2 .DownArrow").bind("click",function(){$(this).hide();$("#sul2 .UpArrow").show();var i1=0;$("#ul2 li").each(function(){if(i1>6){$("#ul2 #Li_"+ i1).removeClass("hidden");}
i1++;});});$("#sul2 .UpArrow").bind("click",function(){$(this).hide();$("#sul2 .DownArrow").show();var i2=0;$("#ul2 li").each(function(){if(i2>6){$("#ul2 #Li_"+ i2).addClass("hidden");}
i2++;});});var j=0;$("#ul3 li").each(function(){if(j>6){$("#ul3 #Li_"+ j).addClass("hidden");}
j++;});$("#sul3 .DownArrow").bind("click",function(){$(this).hide();$("#sul3 .UpArrow").show();var j1=0;$("#ul3 li").each(function(){if(j1>6){$("#ul3 #Li_"+ j1).removeClass("hidden");}
j1++;});});$("#sul3 .UpArrow").bind("click",function(){$(this).hide();$("#sul3 .DownArrow").show();var j2=0;$("#ul3 li").each(function(){if(j2>6){$("#ul3 #Li_"+ j2).addClass("hidden");}
j2++;});});var h=0;$("#ul4 li").each(function(){if($("#ul4").parent().prev().text()!="尺码："){if(h>6){$("#ul4 #Li_"+ h).addClass("hidden");}
h++;}});$("#sul4 .DownArrow").bind("click",function(){$(this).hide();$("#sul4 .UpArrow").show();var h1=0;$("#ul4 li").each(function(){if(h1>6){$("#ul4 #Li_"+ h1).removeClass("hidden");}
h1++;});});$("#sul4 .UpArrow").bind("click",function(){$(this).hide();$("#sul4 .DownArrow").show();var h2=0;$("#ul4 li").each(function(){if(h2>6){$("#ul4 #Li_"+ h2).addClass("hidden");}
h2++;});});$(".ProLi").hover(function(){$(this).addClass("hover");},function(){$(this).removeClass("hover");});$('#women .rightTabs').myTab({operate:'mouseover',time:3000,auto:false,delayTime:0});$('#men .rightTabs').myTab({operate:'mouseover',time:3000,auto:false,delayTime:0});$('#sport .rightTabs').myTab({operate:'mouseover',time:3000,auto:false,delayTime:0});$('#outdoor .rightTabs').myTab({operate:'mouseover',time:3000,auto:false,delayTime:0});$('#child .rightTabs').myTab({operate:'mouseover',time:3000,auto:false,delayTime:0});$(".portrait").hover(function(){$(this).addClass("hovercus");$(".portrait .cusinfo").show();},function(){$(this).removeClass("hovercus");$(".portrait .cusinfo").hide();});$(".collect").hover(function(){$(this).addClass("hover");$(".collecttext").show();},function(){$(this).removeClass("hover");$(".collecttext").hide();});$(".order").hover(function(){$(this).addClass("hoverorder");$(".ordertext").show();},function(){$(this).removeClass("hoverorder");$(".ordertext").hide();});$(".collect").click(function(){var url='http://www.letao.com';var title="乐淘网";AddFavorites(title,url);});$(".attention").hover(function(){$(this).addClass("hoverattent");$(".attention .qrcode").show();},function(){$(this).removeClass("hoverattent");$(".attention .qrcode").hide();});$(".tochat").hover(function(){$(this).addClass("hover");$(this).find(".tochattext").show();},function(){$(this).removeClass("hover");$(this).find(".tochattext").hide();});$(window).scroll(function(){try{if((document.documentElement.scrollTop+ document.body.scrollTop)>200){$(".gotop,.line2").show();}else{$(".gotop,.line2").hide();}}catch(e){}});$(".gotop").click(function(){scroll(0,0);});$(".gotop").hover(function(){$(this).addClass("hovergotop");$(".gotoptitle").show();},function(){$(this).removeClass("hovergotop");$(".gotoptitle").hide();});$('.center .right .tabs').myTab({operate:'mouseover',time:3000,auto:false,delayTime:0});function reHeight(){var winHeight=$(window).height();$(".rightFixed").css("height",winHeight+"px");$(".cart-wrap").css("height",winHeight+"px");}
function reWin(){var winWidth=$(window).width();if(winWidth<=1200){winWidth=1200;}
$(".header").css("width",winWidth+"px");$("#banner").css("width",winWidth+"px");$(".foolter").css("width",winWidth+"px");}
$(window).bind("load",function(){reWin();});$("img").each(function(){if($(this).attr("src")=="http://eiv.baidu.com/hmt/icon/21.gif")
$(this).hide();});$("#winning").textSlider({line:1,speed:500,timer:2000});});function showAuto(){n=n>=(count- 1)?0:++n;$("#banner li").eq(n).trigger('click');}
function SelectProv(aa){$("#Express a.sign").removeClass("sign");$("#prov").text(aa.innerHTML);$(".EDiv").hide();var date=new Date();date.setTime(date.getTime()+(120*60*1000));$.cookie("ckProv",aa.innerHTML,{expires:date,path:'/'});}
function AddFavorites(title,url){var ctrl=(navigator.userAgent.toLowerCase()).indexOf('mac')!=-1?'Command/Cmd':'CTRL';url=encodeURI(url);try{window.external.addFavorite(url,title);}catch(e){try{window.sidebar.addPanel(title,url,"");}catch(e){alert('添加失败\n您可以尝试通过快捷键'+ ctrl+' + D 加入到收藏夹~');}}}